<a href="https://colab.research.google.com/github/2840bongkoch/BSC_DPDM2025/blob/main/midterm_663020284_0_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


นางสาวบงกช เจตวัน 663020284-0 SC-SI

ลิ้งส่งงาน
ไฟล์ผลลัพธ์ข้อมูล csv [ไฟล์ผลลัพธ์ข้อมูล csv](https://drive.google.com/file/d/1O8TZpu5CCYygXzWYLv0p8LakEW8eGAbN/view?usp=sharing)

บันทึกการใช้ AI [บันทึกการใช้ AI](https://kkumail-my.sharepoint.com/personal/bongkoch_j_kkumail_com/Documents/%E0%B8%9A%E0%B8%B1%E0%B8%99%E0%B8%97%E0%B8%B6%E0%B8%81%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B9%80%E0%B8%AD%E0%B9%84%E0%B8%AD.pdf)

โจทย์นี้เป็นงานจริงของสถาบันสารสนเทศและทรัพยกรน้ำ สามารใช้ AI ในหารคำนวณ แต่ต้อง
1. บันทึก prompt ทุกครั้ง
2. อธิบายขั้นตอนอย่างละเอียด
3. อธิบายการทำงานของโค้ดทุกบรรทัก
4. ตรวจสอบความถูกต้องของข้อมูล

หมายหตุ ข้อมูลสูญหาย คือ record ที่ไม่มีในไฟล์เลย (ไม่ใช่ค่า null หรือ Null)

ไฟล์
1. historical_daily_rainfall.csv เป็นข้อมูลปริมาณน้ำฝนรายวันย้อนหลัง (สำหรับคำนวณค่าสถิติ)
2. โฟลเดอร์ Input-(Operation Daily rain from API_2025) เป็นข้อมูลปริมาณน้ำฝนรายวะนที่ต้องการนำมาประมวลผล
3. Stations in the HII.csv รายชื่อสถานีใช้งานได้
4. output_montly_rainfall.csv เป็นผลลัพทธ์ของข้อมูลที่ต้องการ

วิธีการทำ
1. กรองสถานีเฉพาะสถานทีที่อยู่ใน Stations in the model_Hll.csv
2. ลบสถานทีที่มีข้อมูลสูญหาย มากกว่าเท่ากับ 20%
3. เติมข้อมูลด้วยค่า median ของ Day of Year จาก histotical
4. รวมปริมาณฝนแต่ละวันเป็นผลรวมรายเดือน

คำถาม
1. อ่านไฟล์ทั้งหมด แสดงโครงสร้างข้อมูล และอธิบายความหมายของแต่ละคอลัมน์
2. กรองข้อมูลให้เหลือเฉพาะสถานีใน Stations in  the model_Hll.csv แสดงจำนวนสถานีก่อน/หลังกรอง
3. ระบุข้อมูลสูญหาย (record ที่ห่ยไป) ของแต่ละสถานี แสดงจำนวนและสัดส่วน
4. คำสถานีที่มีข้อมูลสูญหาย มากกว่าเท่ากับ 20% แสดงรายชื่อสถานีที่ถูกคัดออกและจำนวนสถานีที่เหลือ
5. เติมข้อมูลหายไปด้วยค่า median ตาม Day of Year จาก histotical แยกตามสถานี ตรวจสอบว่าไม่มี record หายอีก
6. อธิบายเหตุผลที่ใช้ median แทน mean
7. คำนวณผลรวมปริมาณน้ำฝนรายเดือน จัดรูปแบบให้ตรงกับ output_montly_rainfall.csv

สิ่งที่ต้องส่ง
1. ไฟล์ Calab Notebook (.ipynb) ที่มีโ้ดและคำอธิบายครบถ้วน
2. ไฟลผลลัพธ์ข้อมูลรายเดือน (.csv) link Google drive ของไฟล์ output เปิดเป็นสาธารณะ
3. บันทึกการใช้ AI (prompt, ผลลัพทธ์, การปรับแก้, เหตุผล)  Stations in  the model_Hll

In [32]:
stations = pd.read_csv('/content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)/Stations in the model_HII.csv')
stations

Node        Lat        Long
0      ACRU  15.788054  104.642235
1      BBHN   9.536913   98.579490
2      BBUA  17.372976  103.984436
3      BCNG  17.386840  103.290870
4      BDAR  14.587073  102.495190
..      ...        ...         ...
380  YOM003  18.265924  100.177060
381  YOM008  16.708166  100.171780
382  YOM009  16.310750  100.271750
383  YOM010  18.133717  100.124596
384  YOM012  17.021260   99.819710

[385 rows x 3 columns]

# Task
Process daily rainfall data from the Google Drive folder "Input-(Operation Daily rain from API_2025)", filtering stations based on "Stations in the model_HII.csv", identifying and handling missing records (removing stations with greater than or equal to 20% missing data, and imputing the remaining missing data using the median 'Day of Year' from "hii_daily_rain.csv"), then calculate the monthly rainfall totals and save the results to "Y_montly_rain_hii_operation.csv", providing a publicly accessible Google Drive link to the output file along with a comprehensive Colab notebook detailing all steps and explanations.

## Define Google Drive Paths

### Subtask:
จัดเตรียมโค้ดเพื่อกำหนดพาธ (path) สำหรับไฟล์และโฟลเดอร์ข้อมูลทั้งหมดใน Google Drive ที่เชื่อมต่อไว้ โดยจะใช้พาธตามตัวอย่างที่คุณเคยใช้งานสำเร็จแล้ว ซึ่งประกอบด้วย 'hii_daily_rain.csv' (ซึ่งคือ historical daily rainfall), 'Stations in the model_HII.csv' และโฟลเดอร์ 'Input-(Operation Daily rain from API_2025)' เพื่อให้สามารถเข้าถึงข้อมูลได้สะดวก


**Reasoning**:
The subtask requires defining the paths to various files and folders in Google Drive. I will use the `os` module to construct these paths dynamically, ensuring they are correctly defined for subsequent steps.



In [53]:
import os

# Define the base path to your 'midterm' folder in Google Drive
base_path = '/content/drive/MyDrive/Data mining/midterm/'

# Define the path for the folder containing the input daily rainfall data
input_folder_path = os.path.join(base_path, 'Input - (Operation Daily rain from API_ 2025)')

# Define the full path for the historical daily rainfall file (hii_daily_rain.csv)
historical_daily_rainfall_file = os.path.join(input_folder_path, 'hii_daily_rain.csv')

# Define the full path for the stations definition file
stations_model_file = os.path.join(input_folder_path, 'Stations in the model_HII.csv')

# Define the full path for the output monthly rainfall file
output_monthly_rainfall_file = os.path.join(base_path, 'Y_montly_rain_hii_operation.csv')

print(f"Base Path: {base_path}")
print(f"Input Folder Path: {input_folder_path}")
print(f"Historical Daily Rainfall File: {historical_daily_rainfall_file}")
print(f"Stations Model File: {stations_model_file}")
print(f"Output Monthly Rainfall File: {output_monthly_rainfall_file}")

Base Path: /content/drive/MyDrive/Data mining/midterm/
Input Folder Path: /content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)
Historical Daily Rainfall File: /content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)/hii_daily_rain.csv
Stations Model File: /content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)/Stations in the model_HII.csv
Output Monthly Rainfall File: /content/drive/MyDrive/Data mining/midterm/Y_montly_rain_hii_operation.csv


## Load and Inspect Stations Data

### Subtask:
อ่านไฟล์ 'Stations in the model_HII.csv' ซึ่งเป็นรายชื่อสถานีที่ใช้งานได้ เข้ามาเก็บใน DataFrame จากนั้นแสดงผลข้อมูลเบื้องต้น (เช่น 5 แถวแรก, ชนิดข้อมูล, ค่าสถิติเบื้องต้น) และอธิบายความหมายของแต่ละคอลัมน์ในไฟล์นี้เป็นภาษาไทย


**Reasoning**:
The 'Stations in the model_HII.csv' file was already loaded into the 'stations' DataFrame in a previous step. Now, I need to inspect this DataFrame by displaying its head, information, and descriptive statistics as requested by the subtask instructions.



In [54]:
import pandas as pd

# Display the first 5 rows of the DataFrame
print("5 แถวแรกของ DataFrame stations:\n")
print(stations.head())

# Display summary information about the DataFrame
print("\nข้อมูลสรุปของ DataFrame stations:\n")
stations.info()

# Display descriptive statistics of numerical columns
print("\nค่าสถิติเชิงพรรณนาของ DataFrame stations:\n")
print(stations.describe())

5 แถวแรกของ DataFrame stations:

   Node        Lat        Long
0  ACRU  15.788054  104.642235
1  BBHN   9.536913   98.579490
2  BBUA  17.372976  103.984436
3  BCNG  17.386840  103.290870
4  BDAR  14.587073  102.495190

ข้อมูลสรุปของ DataFrame stations:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 385 entries, 0 to 384
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Node    385 non-null    object 
 1   Lat     385 non-null    float64
 2   Long    385 non-null    float64
dtypes: float64(2), object(1)
memory usage: 9.2+ KB

ค่าสถิติเชิงพรรณนาของ DataFrame stations:

              Lat        Long
count  385.000000  385.000000
mean    14.920257  100.828891
std      3.551041    1.556382
min      5.939266   97.935140
25%     13.774838   99.796160
50%     15.632450  100.333910
75%     17.398815  101.774750
max     20.240082  105.501720


### คำอธิบายความหมายของแต่ละคอลัมน์ใน DataFrame `stations`:

- **Node**: รหัสประจำตัวของสถานีวัดปริมาณน้ำฝน (Station ID) ใช้ระบุสถานีแต่ละแห่งที่ไม่ซ้ำกัน
- **Lat**: ละติจูดของสถานีวัดปริมาณน้ำฝน (Latitude) แสดงพิกัดทางภูมิศาสตร์ตามแนวนอน
- **Long**: ลองจิจูดของสถานีวัดปริมาณน้ำฝน (Longitude) แสดงพิกัดทางภูมิศาสตร์ตามแนวตั้ง

### คำอธิบายความหมายของแต่ละคอลัมน์ใน DataFrame `stations`:

- **Node**: รหัสประจำตัวของสถานีวัดปริมาณน้ำฝน (Station ID) ใช้ระบุสถานีแต่ละแห่งที่ไม่ซ้ำกัน
- **Lat**: ละติจูดของสถานีวัดปริมาณน้ำฝน (Latitude) แสดงพิกัดทางภูมิศาสตร์ตามแนวนอน
- **Long**: ลองจิจูดของสถานีวัดปริมาณน้ำฝน (Longitude) แสดงพิกัดทางภูมิศาสตร์ตามแนวตั้ง

## Load and Inspect Historical Daily Rainfall Data

### Subtask:
อ่านไฟล์ 'hii_daily_rain.csv' ซึ่งเป็นข้อมูลปริมาณน้ำฝนรายวันย้อนหลัง (สำหรับคำนวณค่าสถิติ) เข้ามาเก็บใน DataFrame พร้อมทั้งแปลงคอลัมน์วันที่ให้เป็นรูปแบบ Datetime จากนั้นแสดงผลข้อมูลเบื้องต้น (เช่น 5 แถวแรก, ชนิดข้อมูล, ค่าสถิติเบื้องต้น) และอธิบายความหมายของแต่ละคอลัมน์ในไฟล์นี้เป็นภาษาไทย


**Reasoning**:
First, I need to load the 'hii_daily_rain.csv' file into a DataFrame, convert its date column to datetime objects, and then display its head, info, and descriptive statistics as requested. After that, I will provide a markdown explanation for each column.



In [55]:
import pandas as pd

# 1. โหลดไฟล์ 'hii_daily_rain.csv' เข้ามาใน DataFrame ชื่อ historical_df
historical_df = pd.read_csv(historical_daily_rainfall_file)

# 2. แปลงคอลัมน์ที่เก็บข้อมูลวันที่ให้เป็นรูปแบบ Datetime
historical_df['date'] = pd.to_datetime(historical_df['date'], format='%Y-%m-%d')

# 3. แสดง 5 แถวแรกของ DataFrame historical_df
print("\n5 แถวแรกของ DataFrame historical_df:\n")
print(historical_df.head())

# 4. แสดงข้อมูลสรุปของ DataFrame historical_df
print("\nข้อมูลสรุปของ DataFrame historical_df:\n")
historical_df.info()

# 5. แสดงค่าสถิติเชิงพรรณนาสำหรับคอลัมน์ที่เป็นตัวเลขใน DataFrame historical_df
print("\nค่าสถิติเชิงพรรณนาของ DataFrame historical_df:\n")
print(historical_df.describe())

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)/hii_daily_rain.csv'

**Reasoning**:
The previous cell failed with a `FileNotFoundError` because the path to the historical daily rainfall file was incorrect. Based on the initial file list, the correct filename for the historical data is `historical_daily_rainfall.csv`, and it is likely located directly in the `base_path` rather than in the `Input - (Operation Daily rain from API_ 2025)` folder. Therefore, I will redefine the `historical_daily_rainfall_file` variable before attempting to read the CSV.



In [56]:
import pandas as pd
import os

# Redefine base_path if not already defined (ensuring it's available in this cell's scope)
# As per kernel state, base_path is already defined: '/content/drive/MyDrive/Data mining/midterm/'
# However, to ensure the code is self-contained if run independently, or if kernel state changes,
# I'll include its definition here for clarity if it was not explicitly requested to be omitted.
# For this fix, I will assume base_path is available from previous execution.

# Correcting the path for the historical daily rainfall file based on problem description (cell 9JQPxFA1Xa_-)
# which specifies 'historical_daily_rainfall.csv' as the historical file.
# Assuming it's located directly under the base_path.
base_path = '/content/drive/MyDrive/Data mining/midterm/' # Ensuring base_path is available
historical_daily_rainfall_file = os.path.join(base_path, 'historical_daily_rainfall.csv')

# 1. โหลดไฟล์ 'historical_daily_rainfall.csv' เข้ามาใน DataFrame ชื่อ historical_df
historical_df = pd.read_csv(historical_daily_rainfall_file)

# 2. แปลงคอลัมน์ที่เก็บข้อมูลวันที่ให้เป็นรูปแบบ Datetime
historical_df['date'] = pd.to_datetime(historical_df['date'], format='%Y-%m-%d')

# 3. แสดง 5 แถวแรกของ DataFrame historical_df
print("\n5 แถวแรกของ DataFrame historical_df:\n")
print(historical_df.head())

# 4. แสดงข้อมูลสรุปของ DataFrame historical_df
print("\nข้อมูลสรุปของ DataFrame historical_df:\n")
historical_df.info()

# 5. แสดงค่าสถิติเชิงพรรณนาสำหรับคอลัมน์ที่เป็นตัวเลขใน DataFrame historical_df
print("\nค่าสถิติเชิงพรรณนาของ DataFrame historical_df:\n")
print(historical_df.describe())

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Data mining/midterm/historical_daily_rainfall.csv'

**Reasoning**:
The previous attempts failed because the path to the historical daily rainfall file was incorrect. I will correct the `historical_daily_rainfall_file` variable to point to `historical_daily_rainfall.csv` inside the `input_folder_path`, which aligns with the initial file list and the overall data organization. I will also update the comment to reflect the correct filename.



In [57]:
import pandas as pd
import os

# Redefine base_path if not already defined (ensuring it's available in this cell's scope)
# As per kernel state, base_path is already defined: '/content/drive/MyDrive/Data mining/midterm/'
# However, to ensure the code is self-contained if run independently, or if kernel state changes,
# I'll include its definition here for clarity if it was not explicitly requested to be omitted.
# For this fix, I will assume base_path is available from previous execution.

# Correcting the path for the historical daily rainfall file based on problem description (cell 9JQPxFA1Xa_-)
# which specifies 'historical_daily_rainfall.csv' as the historical file, and assuming it's in the input folder.
base_path = '/content/drive/MyDrive/Data mining/midterm/' # Ensuring base_path is available
input_folder_path = os.path.join(base_path, 'Input - (Operation Daily rain from API_ 2025)')
historical_daily_rainfall_file = os.path.join(input_folder_path, 'historical_daily_rainfall.csv')

# 1. โหลดไฟล์ 'historical_daily_rainfall.csv' เข้ามาใน DataFrame ชื่อ historical_df
historical_df = pd.read_csv(historical_daily_rainfall_file)

# 2. แปลงคอลัมน์ที่เก็บข้อมูลวันที่ให้เป็นรูปแบบ Datetime
historical_df['date'] = pd.to_datetime(historical_df['date'], format='%Y-%m-%d')

# 3. แสดง 5 แถวแรกของ DataFrame historical_df
print("\n5 แถวแรกของ DataFrame historical_df:\n")
print(historical_df.head())

# 4. แสดงข้อมูลสรุปของ DataFrame historical_df
print("\nข้อมูลสรุปของ DataFrame historical_df:\n")
historical_df.info()

# 5. แสดงค่าสถิติเชิงพรรณนาสำหรับคอลัมน์ที่เป็นตัวเลขใน DataFrame historical_df
print("\nค่าสถิติเชิงพรรณนาของ DataFrame historical_df:\n")
print(historical_df.describe())

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)/historical_daily_rainfall.csv'

**Reasoning**:
The previous attempts to load the historical daily rainfall data failed due to `FileNotFoundError`. There has been conflicting information regarding the exact filename (`historical_daily_rainfall.csv` vs `hii_daily_rain.csv`) and its location. Based on the task description in cell `ce7b48b6` which explicitly mentions `hii_daily_rain.csv` for imputation, I will assume `hii_daily_rain.csv` is the correct filename for the historical data. Given that previous attempts failed to find it within the `input_folder_path` or as `historical_daily_rainfall.csv` in `base_path`, I will now place `hii_daily_rain.csv` directly in the `base_path`.



In [58]:
import pandas as pd
import os

# Redefine base_path if not already defined (ensuring it's available in this cell's scope)
# As per kernel state, base_path is already defined: '/content/drive/MyDrive/Data mining/midterm/'
# However, to ensure the code is self-contained if run independently, or if kernel state changes,
# I'll include its definition here for clarity if it was not explicitly requested to be omitted.
# For this fix, I will assume base_path is available from previous execution.

# Correcting the path for the historical daily rainfall file based on problem description (cell ce7b48b6)
# which specifies 'hii_daily_rain.csv' as the historical file, and assuming it's located directly under the base_path.
base_path = '/content/drive/MyDrive/Data mining/midterm/' # Ensuring base_path is available
historical_daily_rainfall_file = os.path.join(base_path, 'hii_daily_rain.csv')

# 1. โหลดไฟล์ 'hii_daily_rain.csv' เข้ามาใน DataFrame ชื่อ historical_df
historical_df = pd.read_csv(historical_daily_rainfall_file)

# 2. แปลงคอลัมน์ที่เก็บข้อมูลวันที่ให้เป็นรูปแบบ Datetime
historical_df['date'] = pd.to_datetime(historical_df['date'], format='%Y-%m-%d')

# 3. แสดง 5 แถวแรกของ DataFrame historical_df
print("\n5 แถวแรกของ DataFrame historical_df:\n")
print(historical_df.head())

# 4. แสดงข้อมูลสรุปของ DataFrame historical_df
print("\nข้อมูลสรุปของ DataFrame historical_df:\n")
historical_df.info()

# 5. แสดงค่าสถิติเชิงพรรณนาสำหรับคอลัมน์ที่เป็นตัวเลขใน DataFrame historical_df
print("\nค่าสถิติเชิงพรรณนาของ DataFrame historical_df:\n")
print(historical_df.describe())

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Data mining/midterm/hii_daily_rain.csv'

**Reasoning**:
The previous attempts to load the historical daily rainfall data consistently resulted in a `FileNotFoundError`. The subtask specifically instructs to load 'hii_daily_rain.csv'. While the `Files` section mentions 'historical_daily_rainfall.csv', the `Task` description explicitly references 'hii_daily_rain.csv' for imputation. Therefore, I will prioritize the file name from the subtask and set the path to 'hii_daily_rain.csv' within the `input_folder_path`, as this folder is designated for input data. This path was attempted earlier and failed, suggesting the file might be genuinely missing from the accessible Google Drive location, but this remains the most logical programmatic attempt based on the instructions.



In [59]:
import pandas as pd
import os

# Redefine base_path and input_folder_path to ensure they are consistent with previous definitions
base_path = '/content/drive/MyDrive/Data mining/midterm/'
input_folder_path = os.path.join(base_path, 'Input - (Operation Daily rain from API_ 2025)')

# Correcting the path for the historical daily rainfall file to 'hii_daily_rain.csv'
# and placing it in the input_folder_path as it's an input for calculations.
historical_daily_rainfall_file = os.path.join(input_folder_path, 'hii_daily_rain.csv')

# 1. โหลดไฟล์ 'hii_daily_rain.csv' เข้ามาใน DataFrame ชื่อ historical_df
historical_df = pd.read_csv(historical_daily_rainfall_file)

# 2. แปลงคอลัมน์ที่เก็บข้อมูลวันที่ให้เป็นรูปแบบ Datetime
historical_df['date'] = pd.to_datetime(historical_df['date'], format='%Y-%m-%d')

# 3. แสดง 5 แถวแรกของ DataFrame historical_df
print("\n5 แถวแรกของ DataFrame historical_df:\n")
print(historical_df.head())

# 4. แสดงข้อมูลสรุปของ DataFrame historical_df
print("\nข้อมูลสรุปของ DataFrame historical_df:\n")
historical_df.info()

# 5. แสดงค่าสถิติเชิงพรรณนาสำหรับคอลัมน์ที่เป็นตัวเลขใน DataFrame historical_df
print("\nค่าสถิติเชิงพรรณนาของ DataFrame historical_df:\n")
print(historical_df.describe())

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)/hii_daily_rain.csv'

**Reasoning**:
The previous attempts to load the historical daily rainfall data consistently resulted in a `FileNotFoundError`. To resolve the ambiguity regarding the correct filename (`historical_daily_rainfall.csv` vs `hii_daily_rain.csv`) and its precise location, I will list the contents of both the `base_path` and the `input_folder_path`. This will help identify the actual filename and its directory, allowing for correct file loading in subsequent steps.



In [60]:
import os

# List contents of the base_path
print(f"\nContents of {base_path}:")
for item in os.listdir(base_path):
    print(f"- {item}")

# List contents of the input_folder_path
print(f"\nContents of {input_folder_path}:")
for item in os.listdir(input_folder_path):
    print(f"- {item}")


Contents of /content/drive/MyDrive/Data mining/midterm/:
- Input - (Operation Daily rain from API_ 2025)
- Daily rain - (Statistics 2012-2024)
- Output - (Clean monthly rain - 2025)
- .ipynb_checkpoints

Contents of /content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025):
- 2025-12
- Stations in the model_HII.csv
- 2025-08
- 2025-10
- 2025-07
- 2025-09
- 2025-11


**Reasoning**:
The `os.listdir()` output from the previous step revealed a folder named 'Daily rain - (Statistics 2012-2024)' in the `base_path`. Given that the initial problem description (cell 9JQPxFA1Xa_-) specified 'historical_daily_rainfall.csv' as the historical rainfall data, it is highly probable that this file is located inside this new folder. I will update the `historical_daily_rainfall_file` path accordingly to attempt loading the file from this more logical location and then proceed with the rest of the subtask instructions.



In [61]:
import pandas as pd
import os

# Redefine base_path if not already defined (ensuring it's available in this cell's scope)
base_path = '/content/drive/MyDrive/Data mining/midterm/'

# Correcting the path for the historical daily rainfall file
# Based on the os.listdir output, 'Daily rain - (Statistics 2012-2024)' seems like the correct folder.
# And the file name is 'historical_daily_rainfall.csv' as per problem description.
historical_data_folder = os.path.join(base_path, 'Daily rain - (Statistics 2012-2024)')
historical_daily_rainfall_file = os.path.join(historical_data_folder, 'historical_daily_rainfall.csv')

# 1. โหลดไฟล์ 'historical_daily_rainfall.csv' เข้ามาใน DataFrame ชื่อ historical_df
historical_df = pd.read_csv(historical_daily_rainfall_file)

# 2. แปลงคอลัมน์ที่เก็บข้อมูลวันที่ให้เป็นรูปแบบ Datetime
historical_df['date'] = pd.to_datetime(historical_df['date'], format='%Y-%m-%d')

# 3. แสดง 5 แถวแรกของ DataFrame historical_df
print("\n5 แถวแรกของ DataFrame historical_df:\n")
print(historical_df.head())

# 4. แสดงข้อมูลสรุปของ DataFrame historical_df
print("\nข้อมูลสรุปของ DataFrame historical_df:\n")
historical_df.info()

# 5. แสดงค่าสถิติเชิงพรรณนาสำหรับคอลัมน์ที่เป็นตัวเลขใน DataFrame historical_df
print("\nค่าสถิติเชิงพรรณนาของ DataFrame historical_df:\n")
print(historical_df.describe())

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Data mining/midterm/Daily rain - (Statistics 2012-2024)/historical_daily_rainfall.csv'

**Reasoning**:
The previous attempts to load the historical daily rainfall data continuously failed, even after inspecting the parent directories. To definitively locate the correct historical data file, I will list the contents of the 'Daily rain - (Statistics 2012-2024)' folder, as this is the most probable location based on its name and previous directory listings.



In [62]:
import os

# Define the folder path for historical data
base_path = '/content/drive/MyDrive/Data mining/midterm/'
historical_data_folder = os.path.join(base_path, 'Daily rain - (Statistics 2012-2024)')

# List contents of the historical data folder
print(f"\nContents of {historical_data_folder}:")
if os.path.exists(historical_data_folder):
    for item in os.listdir(historical_data_folder):
        print(f"- {item}")
else:
    print(f"Folder not found: {historical_data_folder}")


Contents of /content/drive/MyDrive/Data mining/midterm/Daily rain - (Statistics 2012-2024):
- hii_daily_rain.csv


**Reasoning**:
Based on the `os.listdir()` output from the previous step, the historical daily rainfall file is definitively named 'hii_daily_rain.csv' and is located within the 'Daily rain - (Statistics 2012-2024)' folder. I will now use this corrected path to load the data, convert the date column, and display its head, info, and descriptive statistics as requested by the subtask.



In [63]:
import pandas as pd
import os

# Redefine base_path and historical_data_folder to ensure consistency
base_path = '/content/drive/MyDrive/Data mining/midterm/'
historical_data_folder = os.path.join(base_path, 'Daily rain - (Statistics 2012-2024)')

# Correcting the path for the historical daily rainfall file based on the os.listdir output
historical_daily_rainfall_file = os.path.join(historical_data_folder, 'hii_daily_rain.csv')

# 1. โหลดไฟล์ 'hii_daily_rain.csv' เข้ามาใน DataFrame ชื่อ historical_df
historical_df = pd.read_csv(historical_daily_rainfall_file)

# 2. แปลงคอลัมน์ที่เก็บข้อมูลวันที่ให้เป็นรูปแบบ Datetime
historical_df['date'] = pd.to_datetime(historical_df['date'], format='%Y-%m-%d')

# 3. แสดง 5 แถวแรกของ DataFrame historical_df
print("\n5 แถวแรกของ DataFrame historical_df:\n")
print(historical_df.head())

# 4. แสดงข้อมูลสรุปของ DataFrame historical_df
print("\nข้อมูลสรุปของ DataFrame historical_df:\n")
historical_df.info()

# 5. แสดงค่าสถิติเชิงพรรณนาสำหรับคอลัมน์ที่เป็นตัวเลขใน DataFrame historical_df
print("\nค่าสถิติเชิงพรรณนาของ DataFrame historical_df:\n")
print(historical_df.describe())

KeyError: 'date'

**Reasoning**:
The previous code failed with a `KeyError: 'date'` because the column containing date information in `historical_df` is named `measure_datetime`, not `date`. I will correct the column name and the datetime format string to properly parse the `measure_datetime` column.



In [64]:
import pandas as pd
import os

# Redefine base_path and historical_data_folder to ensure consistency
base_path = '/content/drive/MyDrive/Data mining/midterm/'
historical_data_folder = os.path.join(base_path, 'Daily rain - (Statistics 2012-2024)')

# Correcting the path for the historical daily rainfall file based on the os.listdir output
historical_daily_rainfall_file = os.path.join(historical_data_folder, 'hii_daily_rain.csv')

# 1. โหลดไฟล์ 'hii_daily_rain.csv' เข้ามาใน DataFrame ชื่อ historical_df
historical_df = pd.read_csv(historical_daily_rainfall_file)

# 2. แปลงคอลัมน์ที่เก็บข้อมูลวันที่ให้เป็นรูปแบบ Datetime
historical_df['measure_datetime'] = pd.to_datetime(historical_df['measure_datetime'], format='%Y-%m-%d %H:%M:%S%z')

# 3. แสดง 5 แถวแรกของ DataFrame historical_df
print("\n5 แถวแรกของ DataFrame historical_df:\n")
print(historical_df.head())

# 4. แสดงข้อมูลสรุปของ DataFrame historical_df
print("\nข้อมูลสรุปของ DataFrame historical_df:\n")
historical_df.info()

# 5. แสดงค่าสถิติเชิงพรรณนาสำหรับคอลัมน์ที่เป็นตัวเลขใน DataFrame historical_df
print("\nค่าสถิติเชิงพรรณนาของ DataFrame historical_df:\n")
print(historical_df.describe())


5 แถวแรกของ DataFrame historical_df:

  station_code          measure_datetime  data station_name   latitude  \
0         ABRT 2012-01-01 07:00:00+07:00   0.0   วัดเวฬุวัน  16.054785   
1         ABRT 2012-01-03 07:00:00+07:00   0.0   วัดเวฬุวัน  16.054785   
2         ABRT 2012-01-06 07:00:00+07:00   0.0   วัดเวฬุวัน  16.054785   
3         ABRT 2012-01-07 07:00:00+07:00   0.0   วัดเวฬุวัน  16.054785   
4         ABRT 2012-01-08 07:00:00+07:00   0.0   วัดเวฬุวัน  16.054785   

   longitude quality_flag basin           sub_basin      tambon  \
0  103.66429            U    ชี  ลำน้ำชีส่วนที่ 4/2  เหนือเมือง   
1  103.66429            U    ชี  ลำน้ำชีส่วนที่ 4/2  เหนือเมือง   
2  103.66429            U    ชี  ลำน้ำชีส่วนที่ 4/2  เหนือเมือง   
3  103.66429            U    ชี  ลำน้ำชีส่วนที่ 4/2  เหนือเมือง   
4  103.66429            U    ชี  ลำน้ำชีส่วนที่ 4/2  เหนือเมือง   

          amphoe  province       data_type  
0  เมืองร้อยเอ็ด  ร้อยเอ็ด  rainfall_daily  
1  เมืองร้อยเอ็ด  ร้อยเ

### คำอธิบายความหมายของแต่ละคอลัมน์ใน DataFrame `historical_df`:

- **station_code (Node)**: รหัสประจำตัวของสถานีวัดปริมาณน้ำฝน ใช้ระบุสถานีแต่ละแห่งที่ไม่ซ้ำกัน
- **measure_datetime (date)**: วันที่และเวลาที่ทำการวัดปริมาณน้ำฝน โดยถูกแปลงให้อยู่ในรูปแบบ Datetime
- **data (rain_mm)**: ปริมาณน้ำฝนที่วัดได้ในแต่ละวัน มีหน่วยเป็นมิลลิเมตร

### คำอธิบายความหมายของแต่ละคอลัมน์ใน DataFrame `historical_df`:

- **station_code (Node)**: รหัสประจำตัวของสถานีวัดปริมาณน้ำฝน ใช้ระบุสถานีแต่ละแห่งที่ไม่ซ้ำกัน
- **measure_datetime (date)**: วันที่และเวลาที่ทำการวัดปริมาณน้ำฝน โดยถูกแปลงให้อยู่ในรูปแบบ Datetime
- **data (rain_mm)**: ปริมาณน้ำฝนที่วัดได้ในแต่ละวัน มีหน่วยเป็นมิลลิเมตร

### คำอธิบายความหมายของแต่ละคอลัมน์ใน DataFrame `historical_df`:

- **station_code (Node)**: รหัสประจำตัวของสถานีวัดปริมาณน้ำฝน ใช้ระบุสถานีแต่ละแห่งที่ไม่ซ้ำกัน
- **measure_datetime (date)**: วันที่และเวลาที่ทำการวัดปริมาณน้ำฝน โดยถูกแปลงให้อยู่ในรูปแบบ Datetime
- **data (rain_mm)**: ปริมาณน้ำฝนที่วัดได้ในแต่ละวัน มีหน่วยเป็นมิลลิเมตร


### คำอธิบายความหมายของแต่ละคอลัมน์ใน DataFrame `historical_df`:

- **station_code (Node)**: รหัสประจำตัวของสถานีวัดปริมาณน้ำฝน ใช้ระบุสถานีแต่ละแห่งที่ไม่ซ้ำกัน
- **measure_datetime (date)**: วันที่และเวลาที่ทำการวัดปริมาณน้ำฝน โดยถูกแปลงให้อยู่ในรูปแบบ Datetime
- **data (rain_mm)**: ปริมาณน้ำฝนที่วัดได้ในแต่ละวัน มีหน่วยเป็นมิลลิเมตร


## Load and Inspect Operational Daily Rainfall Data

### Subtask:
อ่านไฟล์ทั้งหมดในโฟลเดอร์ 'Input-(Operation Daily rain from API_2025)' ที่ไม่ได้เป็นไฟล์เฉพาะ (เช่น historical, stations, output) และถือว่าเป็นไฟล์ข้อมูลปริมาณน้ำฝนรายวันที่ต้องการประมวลผล (แม้ว่าจะไม่มีนามสกุล .csv ก็ตาม) มารวมกันใน DataFrame เดียว พร้อมทั้งแปลงคอลัมน์วันที่ให้เป็นรูปแบบ Datetime และคอลัมน์ปริมาณน้ำฝนให้เป็นตัวเลข จากนั้นแสดงผลข้อมูลเบื้องต้น (เช่น 5 แถวแรก, ชนิดข้อมูล, ค่าสถิติเบื้องต้น) และอธิบายความหมายของแต่ละคอลัมน์ในไฟล์นี้เป็นภาษาไทย


**Reasoning**:
The previous steps successfully loaded the historical daily rainfall data. Now, as per the subtask, I need to load all operational daily rainfall data files from the 'Input-(Operation Daily rain from API_2025)' folder, filter out specific files, and then concatenate them into a single DataFrame for inspection. I will also handle datetime and numeric conversions for the relevant columns.



In [65]:
import os
import pandas as pd

# 1. สร้างลิสต์เปล่าชื่อ operational_data_frames
operational_data_frames = []

# 2. กำหนดลิสต์ของชื่อไฟล์ที่ไม่ต้องการประมวลผล
# The variable `input_folder_path` and `stations_model_file` are already defined.
# For `historical_daily_rainfall_file`, in this context, the request implies
# excluding it if found within the operational input folder. The actual historical_daily_rainfall_file
# was found elsewhere, but for robustness, we'll keep its potential filename in the excluded list.
excluded_filenames = [
    os.path.basename(stations_model_file), # e.g., 'Stations in the model_HII.csv'
    'hii_daily_rain.csv', # As per general task description and for imputation
    'historical_daily_rainfall.csv' # For completeness if it were mistakenly placed here
]

# To verify the contents of the folder for dynamic exclusion if necessary
# print(f"\nContents of {input_folder_path}:")
# for item in os.listdir(input_folder_path):
#     print(f"- {item}")

# 3. วนลูปอ่านไฟล์ทั้งหมดใน input_folder_path
print(f"Reading files from: {input_folder_path}")
for filename in os.listdir(input_folder_path):
    # Check if the file is an actual file and not a directory
    file_path = os.path.join(input_folder_path, filename)
    if os.path.isfile(file_path):
        # Check if the filename is in the excluded list
        if filename in excluded_filenames:
            print(f"Skipping excluded file: {filename}")
            continue

        # Check if the file is a CSV. The instruction says "แม้ว่าจะไม่มีนามสกุล .csv ก็ตาม" meaning it might not have .csv extension.
        # However, to avoid errors with non-csv files, we will try to read it as CSV and handle errors.
        # For now, let's assume valid operational data files are intended to be CSVs that might sometimes lack the extension,
        # or the problem implies they are monthly folders containing daily CSVs.
        # Given the previous `os.listdir(input_folder_path)` output had `2025-12`, `2025-08` etc., these are likely folders.
        # The subtask says "อ่านไฟล์ทั้งหมดในโฟลเดอร์", implying individual files are to be read.
        # Let's adjust this to read files within these monthly folders if they are CSVs, or if they directly contain data.
        # For this step, I will assume the operational files are directly within 'input_folder_path' and are CSVs by nature if they are not in the excluded list.

        # The previous os.listdir output showed folders like '2025-12', '2025-08', etc.
        # This suggests the operational daily rainfall data is likely *inside* these monthly folders.
        # The instruction "อ่านไฟล์ทั้งหมดในโฟลเดอร์ 'Input-(Operation Daily rain from API_2025)'" could mean files directly in it,
        # or recursively within subfolders. Given the output, it's likely subfolders.
        # However, the task implies these are daily rainfall files, so let's check for `.csv` extension, and if not present, assume it is not an operational file.

        if not filename.endswith('.csv'):
            print(f"Skipping non-CSV file: {filename}")
            continue

        try:
            temp_df = pd.read_csv(file_path)
            print(f"Successfully loaded {filename}")

            # Convert 'measure_datetime' to datetime
            # Check if 'measure_datetime' column exists before conversion
            if 'measure_datetime' in temp_df.columns:
                temp_df['measure_datetime'] = pd.to_datetime(temp_df['measure_datetime'], format='%Y-%m-%d %H:%M:%S%z')
            else:
                print(f"Warning: 'measure_datetime' column not found in {filename}. Skipping datetime conversion.")

            # Convert 'data' column to numeric
            if 'data' in temp_df.columns:
                temp_df['data'] = pd.to_numeric(temp_df['data'], errors='coerce')
            else:
                print(f"Warning: 'data' column not found in {filename}. Skipping numeric conversion.")

            operational_data_frames.append(temp_df)
        except Exception as e:
            print(f"Error reading {filename}: {e}")
    else:
        # It's a directory, not a file, so we skip it for this direct file loading step
        print(f"Skipping directory: {filename}")

# 4. รวม DataFrame ทั้งหมดในลิสต์ operational_data_frames เข้าด้วยกัน
if operational_data_frames:
    operational_daily_rainfall_df = pd.concat(operational_data_frames, ignore_index=True)
    print("\nAll operational daily rainfall data concatenated.")

    # 5. แสดง 5 แถวแรกของ operational_daily_rainfall_df
    print("\n5 แถวแรกของ DataFrame operational_daily_rainfall_df:\n")
    print(operational_daily_rainfall_df.head())

    # 6. แสดงข้อมูลสรุปของ operational_daily_rainfall_df
    print("\nข้อมูลสรุปของ DataFrame operational_daily_rainfall_df:\n")
    operational_daily_rainfall_df.info()

    # 7. แสดงค่าสถิติเชิงพรรณนาสำหรับคอลัมน์ที่เป็นตัวเลขใน operational_daily_rainfall_df
    print("\nค่าสถิติเชิงพรรณนาของ DataFrame operational_daily_rainfall_df:\n")
    print(operational_daily_rainfall_df.describe())
else:
    print("No operational daily rainfall data files were found or processed.")
    # Initialize an empty DataFrame if no files were processed
    operational_daily_rainfall_df = pd.DataFrame()

Reading files from: /content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)
Skipping directory: 2025-12
Skipping excluded file: Stations in the model_HII.csv
Skipping directory: 2025-08
Skipping directory: 2025-10
Skipping directory: 2025-07
Skipping directory: 2025-09
Skipping directory: 2025-11
No operational daily rainfall data files were found or processed.


**Reasoning**:
The previous code failed to load operational daily rainfall data because the files are located within monthly subfolders inside the `input_folder_path`, not directly in it. I need to modify the code to recursively traverse these subfolders, identify potential data files, and then attempt to read them into DataFrames while applying the specified transformations and exclusions.



In [66]:
import os
import pandas as pd

# 1. สร้างลิสต์เปล่าชื่อ operational_data_frames
operational_data_frames = []

# 2. กำหนดลิสต์ของชื่อไฟล์ที่ไม่ต้องการประมวลผล
# The variable `input_folder_path` and `stations_model_file` are already defined.
# For `historical_daily_rainfall_file`, in this context, the request implies
# excluding it if found within the operational input folder.
excluded_filenames = [
    os.path.basename(stations_model_file), # e.g., 'Stations in the model_HII.csv'
    'hii_daily_rain.csv', # As per general task description and for imputation
    'historical_daily_rainfall.csv' # For completeness if it were mistakenly placed here
]

# 3. วนลูปอ่านไฟล์ทั้งหมดใน input_folder_path และ sub-folders
print(f"Searching for operational daily rainfall files in: {input_folder_path}")
for root, dirs, files in os.walk(input_folder_path):
    for filename in files:
        # Construct the full path to the file
        file_path = os.path.join(root, filename)

        # Check if the filename is in the excluded list (base filename only)
        if filename in excluded_filenames:
            print(f"Skipping excluded file: {filename}")
            continue

        # Check if the file has a .csv extension or if it's meant to be read as a CSV
        # The instruction says "แม้ว่าจะไม่มีนามสกุล .csv ก็ตาม" meaning it might not have .csv extension.
        # To handle this, we'll try to read all non-excluded files as CSVs and catch errors.

        try:
            temp_df = pd.read_csv(file_path)
            print(f"Successfully loaded {filename} from {root}")

            # Convert 'measure_datetime' to datetime
            # Check if 'measure_datetime' column exists before conversion
            if 'measure_datetime' in temp_df.columns:
                temp_df['measure_datetime'] = pd.to_datetime(temp_df['measure_datetime'], format='%Y-%m-%d %H:%M:%S%z', errors='coerce')
                # Drop rows where datetime conversion failed if any
                temp_df.dropna(subset=['measure_datetime'], inplace=True)
            else:
                print(f"Warning: 'measure_datetime' column not found in {filename}. Skipping datetime conversion.")

            # Convert 'data' column to numeric
            if 'data' in temp_df.columns:
                temp_df['data'] = pd.to_numeric(temp_df['data'], errors='coerce')
                # Drop rows where data conversion failed if any
                temp_df.dropna(subset=['data'], inplace=True)
            else:
                print(f"Warning: 'data' column not found in {filename}. Skipping numeric conversion.")

            # Only append if the DataFrame has actual data after processing
            if not temp_df.empty:
                operational_data_frames.append(temp_df)
            else:
                print(f"Warning: {filename} became empty after processing. Skipping.")

        except Exception as e:
            print(f"Error reading or processing {filename} from {root}: {e}")

# 4. รวม DataFrame ทั้งหมดในลิสต์ operational_data_frames เข้าด้วยกัน
if operational_data_frames:
    operational_daily_rainfall_df = pd.concat(operational_data_frames, ignore_index=True)
    print("\nAll operational daily rainfall data concatenated.")

    # 5. แสดง 5 แถวแรกของ operational_daily_rainfall_df
    print("\n5 แถวแรกของ DataFrame operational_daily_rainfall_df:\n")
    print(operational_daily_rainfall_df.head())

    # 6. แสดงข้อมูลสรุปของ operational_daily_rainfall_df
    print("\nข้อมูลสรุปของ DataFrame operational_daily_rainfall_df:\n")
    operational_daily_rainfall_df.info()

    # 7. แสดงค่าสถิติเชิงพรรณนาสำหรับคอลัมน์ที่เป็นตัวเลขใน operational_daily_rainfall_df
    print("\nค่าสถิติเชิงพรรณนาของ DataFrame operational_daily_rainfall_df:\n")
    print(operational_daily_rainfall_df.describe())
else:
    print("No operational daily rainfall data files were found or processed.")
    # Initialize an empty DataFrame if no files were processed
    operational_daily_rainfall_df = pd.DataFrame()

Searching for operational daily rainfall files in: /content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)
Skipping excluded file: Stations in the model_HII.csv
Successfully loaded HII_daily_rainfall_2025-12-02.csv from /content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)/2025-12
Successfully loaded HII_daily_rainfall_2025-12-03.csv from /content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)/2025-12
Successfully loaded HII_daily_rainfall_2025-12-09.csv from /content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)/2025-12
Successfully loaded HII_daily_rainfall_2025-12-04.csv from /content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)/2025-12
Successfully loaded HII_daily_rainfall_2025-12-08.csv from /content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)/2025-12
Successfully loaded HII_da

**Reasoning**:
The previous code failed to load operational daily rainfall data because the correct column names for datetime and rainfall amount (`rainfall_datetime` and `rainfall_value`) were not being used, leading to DataFrames becoming empty after dropping missing values. I will modify the code to prioritize these column names for conversion and ensure the data is loaded correctly, then proceed to display the head, info, and descriptive statistics as requested.



In [67]:
import os
import pandas as pd

# 1. สร้างลิสต์เปล่าชื่อ operational_data_frames
operational_data_frames = []

# 2. กำหนดลิสต์ของชื่อไฟล์ที่ไม่ต้องการประมวลผล
# The variable `input_folder_path` and `stations_model_file` are already defined.
# For `historical_daily_rainfall_file`, in this context, the request implies
# excluding it if found within the operational input folder.
excluded_filenames = [
    os.path.basename(stations_model_file), # e.g., 'Stations in the model_HII.csv'
    'hii_daily_rain.csv', # As per general task description and for imputation
    'historical_daily_rainfall.csv' # For completeness if it were mistakenly placed here
]

# 3. วนลูปอ่านไฟล์ทั้งหมดใน input_folder_path และ sub-folders
print(f"Searching for operational daily rainfall files in: {input_folder_path}")
for root, dirs, files in os.walk(input_folder_path):
    for filename in files:
        # Construct the full path to the file
        file_path = os.path.join(root, filename)

        # Check if the filename is in the excluded list (base filename only)
        if filename in excluded_filenames:
            print(f"Skipping excluded file: {filename}")
            continue

        # Check if the file has a .csv extension. Only process CSVs here.
        if not filename.lower().endswith('.csv'):
            print(f"Skipping non-CSV file: {filename}")
            continue

        try:
            temp_df = pd.read_csv(file_path)
            # print(f"Successfully loaded {filename} from {root}")

            # Determine the correct datetime column
            datetime_col = None
            if 'rainfall_datetime' in temp_df.columns:
                datetime_col = 'rainfall_datetime'
            elif 'measure_datetime' in temp_df.columns:
                datetime_col = 'measure_datetime'

            if datetime_col:
                temp_df[datetime_col] = pd.to_datetime(temp_df[datetime_col], errors='coerce')
                # Rename to a standard 'date' column for consistency if needed later, but for now, use original
            else:
                print(f"Warning: Neither 'rainfall_datetime' nor 'measure_datetime' column found in {filename}. Skipping datetime conversion.")
                continue # Skip if no date column is found

            # Determine the correct rainfall data column
            data_col = None
            if 'rainfall_value' in temp_df.columns:
                data_col = 'rainfall_value'
            elif 'data' in temp_df.columns:
                data_col = 'data'

            if data_col:
                temp_df[data_col] = pd.to_numeric(temp_df[data_col], errors='coerce')
                # Rename to a standard 'data' column for consistency if needed later, but for now, use original
            else:
                print(f"Warning: Neither 'rainfall_value' nor 'data' column found in {filename}. Skipping numeric conversion.")
                continue # Skip if no data column is found

            # Drop rows where critical columns (datetime or data) are NaN after conversion
            if datetime_col and data_col:
                temp_df.dropna(subset=[datetime_col, data_col], inplace=True)

            # Only append if the DataFrame has actual data after processing
            if not temp_df.empty:
                operational_data_frames.append(temp_df)
                print(f"Successfully loaded and processed {filename} from {root}. Rows: {len(temp_df)}")
            else:
                print(f"Warning: {filename} became empty after processing. Skipping.")

        except Exception as e:
            print(f"Error reading or processing {filename} from {root}: {e}")

# 4. รวม DataFrame ทั้งหมดในลิสต์ operational_data_frames เข้าด้วยกัน
if operational_data_frames:
    operational_daily_rainfall_df = pd.concat(operational_data_frames, ignore_index=True)
    print("\nAll operational daily rainfall data concatenated.")

    # 5. แสดง 5 แถวแรกของ operational_daily_rainfall_df
    print("\n5 แถวแรกของ DataFrame operational_daily_rainfall_df:\n")
    print(operational_daily_rainfall_df.head())

    # 6. แสดงข้อมูลสรุปของ operational_daily_rainfall_df
    print("\nข้อมูลสรุปของ DataFrame operational_daily_rainfall_df:\n")
    operational_daily_rainfall_df.info()

    # 7. แสดงค่าสถิติเชิงพรรณนาสำหรับคอลัมน์ที่เป็นตัวเลขใน operational_daily_rainfall_df
    print("\nค่าสถิติเชิงพรรณนาของ DataFrame operational_daily_rainfall_df:\n")
    print(operational_daily_rainfall_df.describe())
else:
    print("No operational daily rainfall data files were found or processed.")
    # Initialize an empty DataFrame if no files were processed
    operational_daily_rainfall_df = pd.DataFrame()

Searching for operational daily rainfall files in: /content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)
Skipping excluded file: Stations in the model_HII.csv
Successfully loaded and processed HII_daily_rainfall_2025-12-02.csv from /content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)/2025-12. Rows: 1055
Successfully loaded and processed HII_daily_rainfall_2025-12-03.csv from /content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)/2025-12. Rows: 1055
Successfully loaded and processed HII_daily_rainfall_2025-12-09.csv from /content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)/2025-12. Rows: 1064
Successfully loaded and processed HII_daily_rainfall_2025-12-04.csv from /content/drive/MyDrive/Data mining/midterm/Input - (Operation Daily rain from API_ 2025)/2025-12. Rows: 1054
Successfully loaded and processed HII_daily_rainfall_2025-12-08.csv from /cont

### คำอธิบายความหมายของแต่ละคอลัมน์ใน DataFrame `operational_daily_rainfall_df`:

- **rainfall_datetime**: วันที่และเวลาที่ทำการวัดปริมาณน้ำฝน โดยเป็นข้อมูลหลักที่ถูกแปลงให้อยู่ในรูปแบบ Datetime
- **rainfall_datetime_calc**: คอลัมน์เสริมที่อาจมาจากข้อมูลวันที่และเวลาเดิม ซึ่งมีรูปแบบการแสดงผลเป็น Object
- **rainfall_value**: ปริมาณน้ำฝนที่วัดได้ในแต่ละวัน มีหน่วยเป็นมิลลิเมตร
- **tele_station_id**: รหัสประจำตัวของสถานีวัดปริมาณน้ำฝนในระบบโทรมาตร (Telemetry Station ID)
- **tele_station_oldcode**: รหัสประจำตัวเดิมของสถานีวัดปริมาณน้ำฝนในระบบโทรมาตร (Old Telemetry Station Code)
- **measure_datetime**: คอลัมน์ที่อาจมาจากข้อมูลวันที่และเวลาเดิมในรูปแบบข้อความ (Object)

## Filter Stations

### Subtask:
กรองข้อมูลปริมาณน้ำฝนรายวันในส่วนของข้อมูลที่ต้องการประมวลผล (Operational Daily Rainfall Data) ให้เหลือเฉพาะสถานีที่มีอยู่ในไฟล์ 'Stations in the model_HII.csv' เท่านั้น โดยจะแสดงจำนวนสถานีก่อนและหลังการกรองเพื่อยืนยันผลลัพธ์


**Reasoning**:
I need to filter the `operational_daily_rainfall_df` to keep only the stations present in the `stations` DataFrame. First, I will extract the unique station IDs from the `stations` DataFrame. Then, I will display the number of unique stations in `operational_daily_rainfall_df` before filtering, perform the filtering, and finally display the number of unique stations after filtering to show the effect of the operation.



In [68]:
import pandas as pd

# 1. รับค่า Node ทั้งหมดจาก DataFrame stations
station_nodes = stations['Node'].unique()

# 2. แสดงจำนวนสถานีที่ไม่ซ้ำกันใน operational_daily_rainfall_df ก่อนการกรอง
initial_unique_stations = operational_daily_rainfall_df['tele_station_oldcode'].nunique()
print(f"จำนวนสถานีที่ไม่ซ้ำกันใน operational_daily_rainfall_df ก่อนการกรอง: {initial_unique_stations}")

# 3. กรอง operational_daily_rainfall_df โดยเลือกเฉพาะแถวที่คอลัมน์ tele_station_oldcode มีค่าตรงกับ Node ที่อยู่ใน DataFrame stations
filtered_operational_df = operational_daily_rainfall_df[operational_daily_rainfall_df['tele_station_oldcode'].isin(station_nodes)].copy()

# 4. แสดงจำนวนสถานีที่ไม่ซ้ำกันใน operational_daily_rainfall_df หลังจากที่ได้กรองแล้ว
final_unique_stations = filtered_operational_df['tele_station_oldcode'].nunique()
print(f"จำนวนสถานีที่ไม่ซ้ำกันใน operational_daily_rainfall_df หลังการกรอง: {final_unique_stations}")

print("Filtering completed. Displaying head of filtered_operational_df for inspection.")
print(filtered_operational_df.head())

จำนวนสถานีที่ไม่ซ้ำกันใน operational_daily_rainfall_df ก่อนการกรอง: 1514
จำนวนสถานีที่ไม่ซ้ำกันใน operational_daily_rainfall_df หลังการกรอง: 384
Filtering completed. Displaying head of filtered_operational_df for inspection.
            rainfall_datetime     rainfall_datetime_calc  rainfall_value  \
1   2025-12-03 00:00:00+07:00  2025-12-02T07:00:00+07:00             0.0   
9   2025-12-03 00:00:00+07:00  2025-12-02T07:00:00+07:00             0.0   
10  2025-12-03 00:00:00+07:00  2025-12-02T07:00:00+07:00             0.0   
13  2025-12-03 00:00:00+07:00  2025-12-02T07:00:00+07:00             0.0   
169 2025-12-03 00:00:00+07:00  2025-12-02T07:00:00+07:00             0.0   

     tele_station_id tele_station_oldcode measure_datetime  
1              135.0               VLGE03       2025-12-02  
9               43.0                 NOKK       2025-12-02  
10             143.0                 NBON       2025-12-02  
13             119.0                 BNGR       2025-12-02  
169          

## Identify Missing Records

### Subtask:
ระบุ 'ข้อมูลสูญหาย' ในข้อมูลปริมาณน้ำฝนรายวัน (Operational Daily Rainfall Data) ซึ่งหมายถึงวันที่ไม่มีบันทึกข้อมูลเลย (ไม่ใช่ค่าว่างหรือ Null) สำหรับแต่ละสถานี โดยการตรวจสอบช่วงวันที่ของข้อมูลที่มีอยู่และสร้างช่วงวันที่ที่สมบูรณ์ จากนั้นคำนวณจำนวนและสัดส่วนของข้อมูลที่สูญหายสำหรับแต่ละสถานีและแสดงผล


**Reasoning**:
The first step is to rename the 'tele_station_oldcode' column to 'station_code' in the `filtered_operational_df` for consistency with other dataframes and to prepare for grouping operations.



In [69]:
import pandas as pd

# 1. เปลี่ยนชื่อคอลัมน์ 'tele_station_oldcode' ใน filtered_operational_df เป็น 'station_code'
filtered_operational_df = filtered_operational_df.rename(columns={'tele_station_oldcode': 'station_code'})

print("Column 'tele_station_oldcode' renamed to 'station_code'.")
print("Updated columns:", filtered_operational_df.columns)

Column 'tele_station_oldcode' renamed to 'station_code'.
Updated columns: Index(['rainfall_datetime', 'rainfall_datetime_calc', 'rainfall_value',
       'tele_station_id', 'station_code', 'measure_datetime'],
      dtype='object')


**Reasoning**:
I will group the data by station, determine the min and max dates, generate a complete date range, identify actual recorded dates, and then calculate missing records count and percentage for each station, finally displaying the results as requested by the subtask.



In [70]:
import pandas as pd

# Ensure 'rainfall_datetime' is a datetime object
filtered_operational_df['rainfall_datetime'] = pd.to_datetime(filtered_operational_df['rainfall_datetime'])

# 2. สำหรับแต่ละสถานีใน filtered_operational_df ให้ระบุช่วงวันที่ที่มีข้อมูลอยู่จริง (วันเริ่มต้นและวันสิ้นสุด)
station_date_ranges = filtered_operational_df.groupby('station_code')['rainfall_datetime'].agg(['min', 'max']).reset_index()
station_date_ranges.rename(columns={'min': 'start_date', 'max': 'end_date'}, inplace=True)

missing_data_summary = []

# 3. สร้างช่วงวันที่ที่สมบูรณ์สำหรับแต่ละสถานี
# 4. เปรียบเทียบวันที่ที่มีอยู่จริงกับช่วงวันที่ที่สมบูรณ์ เพื่อระบุวันที่ที่ขาดหายไป
# 5. คำนวณจำนวนข้อมูลที่ขาดหายไปและสัดส่วนของข้อมูลที่ขาดหายไป
for index, row in station_date_ranges.iterrows():
    station_code = row['station_code']
    start_date = row['start_date']
    end_date = row['end_date']

    # Generate a complete daily date range for the station
    full_date_range = pd.date_range(start=start_date.normalize(), end=end_date.normalize(), freq='D')
    total_expected_days = len(full_date_range)

    # Get actual recorded dates for the current station
    actual_recorded_dates = filtered_operational_df[filtered_operational_df['station_code'] == station_code]['rainfall_datetime'].dt.normalize().unique()
    actual_recorded_days = len(actual_recorded_dates)

    # Calculate missing days
    missing_records_count = total_expected_days - actual_recorded_days
    missing_records_percentage = (missing_records_count / total_expected_days) * 100 if total_expected_days > 0 else 0

    missing_data_summary.append({
        'station_code': station_code,
        'total_expected_days': total_expected_days,
        'actual_recorded_days': actual_recorded_days,
        'missing_records_count': missing_records_count,
        'missing_records_percentage': missing_records_percentage
    })

# 6. สร้าง DataFrame ใหม่เพื่อเก็บผลลัพธ์
missing_data_df = pd.DataFrame(missing_data_summary)

# 7. แสดง 5 แถวแรกของ DataFrame ผลลัพธ์
print("\n5 แถวแรกของ DataFrame สรุปข้อมูลสูญหาย (missing_data_df):\n")
print(missing_data_df.head())

# แสดงข้อมูลสรุปทางสถิติของคอลัมน์ 'missing_records_percentage'
print("\nค่าสถิติเชิงพรรณนาของ 'missing_records_percentage':\n")
print(missing_data_df['missing_records_percentage'].describe())



5 แถวแรกของ DataFrame สรุปข้อมูลสูญหาย (missing_data_df):

  station_code  total_expected_days  actual_recorded_days  \
0         ACRU                  184                   184   
1         BBHN                  184                   184   
2         BBUA                  184                   169   
3         BCNG                  184                   184   
4         BDAR                  184                   184   

   missing_records_count  missing_records_percentage  
0                      0                    0.000000  
1                      0                    0.000000  
2                     15                    8.152174  
3                      0                    0.000000  
4                      0                    0.000000  

ค่าสถิติเชิงพรรณนาของ 'missing_records_percentage':

count    384.000000
mean       2.520604
std        7.941346
min        0.000000
25%        0.000000
50%        0.000000
75%        0.543478
max       66.847826
Name: missing_records_percent

## Remove Stations with High Missing Data

### Subtask:
คัดสถานีที่มีข้อมูลสูญหาย (ตามที่ระบุในขั้นตอนก่อนหน้า) มากกว่าหรือเท่ากับ 20% ออกจากชุดข้อมูลทั้งหมด โดยจะแสดงรายชื่อสถานีที่ถูกคัดออกและจำนวนสถานีที่เหลืออยู่


**Reasoning**:
I need to identify stations with more than or equal to 20% missing data from `missing_data_df`, then filter `filtered_operational_df` based on these stations, and finally display the affected stations and the counts before and after filtering.



In [71]:
import pandas as pd

# 1. ระบุรหัสสถานี ('station_code') ที่มีค่า 'missing_records_percentage' มากกว่าหรือเท่ากับ 20% จาก DataFrame `missing_data_df`
stations_to_remove_df = missing_data_df[missing_data_df['missing_records_percentage'] >= 20]
stations_to_remove = stations_to_remove_df['station_code'].tolist()

# 2. แสดงรายชื่อสถานีที่ถูกคัดออก (สถานีใน `stations_to_remove`)
print(f"\nรายชื่อสถานีที่ถูกคัดออกเนื่องจากมีข้อมูลสูญหาย >= 20%: {stations_to_remove}")
print(f"จำนวนสถานีที่ถูกคัดออก: {len(stations_to_remove)}")

# 3. แสดงจำนวนสถานีก่อนการคัดออก (จำนวนสถานีที่ไม่ซ้ำกันใน `filtered_operational_df`)
initial_stations_count = filtered_operational_df['station_code'].nunique()
print(f"\nจำนวนสถานีที่ไม่ซ้ำกันในชุดข้อมูลก่อนการคัดออก: {initial_stations_count}")

# 4. กรอง DataFrame `filtered_operational_df` เพื่อลบแถวที่ 'station_code' อยู่ใน `stations_to_remove` ออก
processed_operational_df = filtered_operational_df[~filtered_operational_df['station_code'].isin(stations_to_remove)].copy()

# 5. แสดงจำนวนสถานีที่เหลืออยู่หลังจากคัดออก (จำนวนสถานีที่ไม่ซ้ำกันใน `processed_operational_df`)
final_stations_count = processed_operational_df['station_code'].nunique()
print(f"จำนวนสถานีที่ไม่ซ้ำกันในชุดข้อมูลหลังการคัดออก: {final_stations_count}")

# 6. แสดง 5 แถวแรกของ `processed_operational_df` เพื่อตรวจสอบ
print("\n5 แถวแรกของ DataFrame `processed_operational_df` หลังการคัดออกสถานี:\n")
print(processed_operational_df.head())


รายชื่อสถานีที่ถูกคัดออกเนื่องจากมีข้อมูลสูญหาย >= 20%: ['BKHN', 'BLKO', 'BNLG', 'BSPN', 'CGKM', 'CHI010', 'CHI013', 'CPY010', 'CTKN', 'KKTO', 'MMMO', 'MNRM', 'NEAK', 'NGCG', 'NGPI', 'NKSG', 'SGKW', 'SKE001', 'SKM004', 'SLA002', 'TPI007', 'TUKW']
จำนวนสถานีที่ถูกคัดออก: 22

จำนวนสถานีที่ไม่ซ้ำกันในชุดข้อมูลก่อนการคัดออก: 384
จำนวนสถานีที่ไม่ซ้ำกันในชุดข้อมูลหลังการคัดออก: 362

5 แถวแรกของ DataFrame `processed_operational_df` หลังการคัดออกสถานี:

            rainfall_datetime     rainfall_datetime_calc  rainfall_value  \
1   2025-12-03 00:00:00+07:00  2025-12-02T07:00:00+07:00             0.0   
9   2025-12-03 00:00:00+07:00  2025-12-02T07:00:00+07:00             0.0   
10  2025-12-03 00:00:00+07:00  2025-12-02T07:00:00+07:00             0.0   
13  2025-12-03 00:00:00+07:00  2025-12-02T07:00:00+07:00             0.0   
169 2025-12-03 00:00:00+07:00  2025-12-02T07:00:00+07:00             0.0   

     tele_station_id station_code measure_datetime  
1              135.0       VLGE03      

## Impute Missing Data with Median

### Subtask:
เติมข้อมูลที่สูญหายในข้อมูลปริมาณน้ำฝนรายวันของสถานีที่เหลืออยู่ โดยใช้ค่า Median ของ 'Day of Year' จากข้อมูลน้ำฝนรายวันย้อนหลัง (hii_daily_rain.csv) แยกตามสถานี หากสถานีนั้นไม่มีข้อมูลใน historical จะใช้ค่า median จาก DoY ภาพรวม จากนั้นจะตรวจสอบอีกครั้งเพื่อให้แน่ใจว่าไม่มี record ที่สูญหายอีกต่อไป


**Reasoning**:
The first instruction requires renaming columns in `historical_df` for consistency and converting the datetime column to date-only format. This aligns the historical data with the target format for imputation.



In [72]:
import pandas as pd

# 1. เปลี่ยนชื่อคอลัมน์ใน `historical_df` ให้เป็นมาตรฐาน: เปลี่ยน `measure_datetime` เป็น `date` และ `data` เป็น `rainfall_value`
# พร้อมทั้งแปลงคอลัมน์ `date` ให้เป็นประเภท datetime และตัดเวลาออกให้เหลือแต่วันที่

historical_df_cleaned = historical_df.copy()
historical_df_cleaned = historical_df_cleaned.rename(columns={'measure_datetime': 'date', 'data': 'rainfall_value'})

historical_df_cleaned['date'] = pd.to_datetime(historical_df_cleaned['date']).dt.normalize()

print("Historical DataFrame columns renamed and date column normalized.")
print("New columns:", historical_df_cleaned.columns)
print("5 แถวแรกของ historical_df_cleaned หลังปรับปรุง:")
print(historical_df_cleaned.head())

Historical DataFrame columns renamed and date column normalized.
New columns: Index(['station_code', 'date', 'rainfall_value', 'station_name', 'latitude',
       'longitude', 'quality_flag', 'basin', 'sub_basin', 'tambon', 'amphoe',
       'province', 'data_type'],
      dtype='object')
5 แถวแรกของ historical_df_cleaned หลังปรับปรุง:
  station_code                      date  rainfall_value station_name  \
0         ABRT 2012-01-01 00:00:00+07:00             0.0   วัดเวฬุวัน   
1         ABRT 2012-01-03 00:00:00+07:00             0.0   วัดเวฬุวัน   
2         ABRT 2012-01-06 00:00:00+07:00             0.0   วัดเวฬุวัน   
3         ABRT 2012-01-07 00:00:00+07:00             0.0   วัดเวฬุวัน   
4         ABRT 2012-01-08 00:00:00+07:00             0.0   วัดเวฬุวัน   

    latitude  longitude quality_flag basin           sub_basin      tambon  \
0  16.054785  103.66429            U    ชี  ลำน้ำชีส่วนที่ 4/2  เหนือเมือง   
1  16.054785  103.66429            U    ชี  ลำน้ำชีส่วนที่ 4/2  เหนือ

**Reasoning**:
Now that `historical_df_cleaned` has consistent column names and normalized dates, I will extract the 'DayOfYear' to prepare for calculating median rainfall values for imputation. This is instruction #2 of the subtask.



In [73]:
import pandas as pd

# 2. สร้างคอลัมน์ `DayOfYear` ใน `historical_df_cleaned` โดยดึงค่าวันในรอบปี (Day of Year) ออกมาจากคอลัมน์ `date`.
historical_df_cleaned['DayOfYear'] = historical_df_cleaned['date'].dt.dayofyear

print("Created 'DayOfYear' column in historical_df_cleaned.")
print("5 แถวแรกของ historical_df_cleaned พร้อมคอลัมน์ DayOfYear:")
print(historical_df_cleaned.head())

Created 'DayOfYear' column in historical_df_cleaned.
5 แถวแรกของ historical_df_cleaned พร้อมคอลัมน์ DayOfYear:
  station_code                      date  rainfall_value station_name  \
0         ABRT 2012-01-01 00:00:00+07:00             0.0   วัดเวฬุวัน   
1         ABRT 2012-01-03 00:00:00+07:00             0.0   วัดเวฬุวัน   
2         ABRT 2012-01-06 00:00:00+07:00             0.0   วัดเวฬุวัน   
3         ABRT 2012-01-07 00:00:00+07:00             0.0   วัดเวฬุวัน   
4         ABRT 2012-01-08 00:00:00+07:00             0.0   วัดเวฬุวัน   

    latitude  longitude quality_flag basin           sub_basin      tambon  \
0  16.054785  103.66429            U    ชี  ลำน้ำชีส่วนที่ 4/2  เหนือเมือง   
1  16.054785  103.66429            U    ชี  ลำน้ำชีส่วนที่ 4/2  เหนือเมือง   
2  16.054785  103.66429            U    ชี  ลำน้ำชีส่วนที่ 4/2  เหนือเมือง   
3  16.054785  103.66429            U    ชี  ลำน้ำชีส่วนที่ 4/2  เหนือเมือง   
4  16.054785  103.66429            U    ชี  ลำน้ำชีส่วนที่ 4

**Reasoning**:
Following the subtask instructions, I will now calculate the median `rainfall_value` from `historical_df_cleaned`, grouped by `station_code` and `DayOfYear`, and store the result in a new DataFrame called `station_doy_medians`.



In [74]:
import pandas as pd

# 3. คำนวณค่ามัธยฐาน (median) ของ `rainfall_value` จาก `historical_df_cleaned`
# โดยจัดกลุ่มตาม `station_code` และ `DayOfYear` แล้วเก็บผลลัพธ์ไว้ใน DataFrame ใหม่ชื่อ `station_doy_medians`.
station_doy_medians = historical_df_cleaned.groupby(['station_code', 'DayOfYear'])['rainfall_value'].median().reset_index()

print("Calculated station-specific DayOfYear medians.")
print("5 แถวแรกของ station_doy_medians:")
print(station_doy_medians.head())

Calculated station-specific DayOfYear medians.
5 แถวแรกของ station_doy_medians:
  station_code  DayOfYear  rainfall_value
0         ABRT          1             0.0
1         ABRT          2             0.0
2         ABRT          3             0.0
3         ABRT          4             0.0
4         ABRT          5             0.0


**Reasoning**:
As per instruction #4 of the subtask, I will calculate the overall median rainfall value from `historical_df_cleaned` by grouping only by `DayOfYear`. This will serve as a fallback imputation value for stations that might not have station-specific historical data for a particular DayOfYear.



In [75]:
import pandas as pd

# 4. คำนวณค่ามัธยฐาน (median) ของ `rainfall_value` จาก `historical_df_cleaned`
# โดยจัดกลุ่มเฉพาะตาม `DayOfYear` (สำหรับใช้เป็นค่า fallback) แล้วเก็บผลลัพธ์ไว้ใน DataFrame ใหม่ชื่อ `overall_doy_medians`.
overall_doy_medians = historical_df_cleaned.groupby('DayOfYear')['rainfall_value'].median().reset_index()

print("Calculated overall DayOfYear medians (fallback values).")
print("5 แถวแรกของ overall_doy_medians:")
print(overall_doy_medians.head())

Calculated overall DayOfYear medians (fallback values).
5 แถวแรกของ overall_doy_medians:
   DayOfYear  rainfall_value
0          1             0.0
1          2             0.0
2          3             0.0
3          4             0.0
4          5             0.0


**Reasoning**:
As per instruction #5, I need to create a DataFrame `all_expected_records_df` that contains every date for each station present in `processed_operational_df`, using the start and end dates derived from `missing_data_df` (after filtering out stations that were removed). This will establish a complete timeline for each active station.



In [76]:
import pandas as pd

# 5. สร้าง DataFrame `all_expected_records_df`

# Get the list of station codes that are still in processed_operational_df
active_station_codes = processed_operational_df['station_code'].unique()

# Filter missing_data_df to get start and end dates only for active stations
active_station_date_ranges = missing_data_df[missing_data_df['station_code'].isin(active_station_codes)]

# Initialize a list to store data for all expected records
all_expected_records = []

for index, row in active_station_date_ranges.iterrows():
    station_code = row['station_code']
    start_date = row['start_date'].normalize() # Ensure date-only for consistency
    end_date = row['end_date'].normalize() # Ensure date-only for consistency

    # Generate a complete daily date range for the current station
    date_range = pd.date_range(start=start_date, end=end_date, freq='D')

    # Create a temporary DataFrame for this station's full date range
    temp_df = pd.DataFrame({
        'station_code': station_code,
        'date': date_range
    })
    all_expected_records.append(temp_df)

# Concatenate all temporary DataFrames into all_expected_records_df
if all_expected_records:
    all_expected_records_df = pd.concat(all_expected_records, ignore_index=True)
else:
    all_expected_records_df = pd.DataFrame(columns=['station_code', 'date'])

print("Created all_expected_records_df with complete date ranges for active stations.")
print("5 แถวแรกของ all_expected_records_df:")
print(all_expected_records_df.head())
print("ข้อมูลสรุปของ all_expected_records_df:")
all_expected_records_df.info()

KeyError: 'start_date'

**Reasoning**:
The `KeyError: 'start_date'` occurred because the `active_station_date_ranges` DataFrame, which was derived from `missing_data_df`, did not contain the 'start_date' and 'end_date' columns. These columns were present in `station_date_ranges`. To fix this, I will filter the `station_date_ranges` DataFrame directly using the `active_station_codes` to obtain the correct start and end dates for each active station.



In [77]:
import pandas as pd

# 5. สร้าง DataFrame `all_expected_records_df`

# Get the list of station codes that are still in processed_operational_df
active_station_codes = processed_operational_df['station_code'].unique()

# Filter station_date_ranges to get start and end dates only for active stations
# This ensures 'start_date' and 'end_date' columns are present
active_station_date_ranges = station_date_ranges[station_date_ranges['station_code'].isin(active_station_codes)]

# Initialize a list to store data for all expected records
all_expected_records = []

for index, row in active_station_date_ranges.iterrows():
    station_code = row['station_code']
    start_date = row['start_date'].normalize() # Ensure date-only for consistency
    end_date = row['end_date'].normalize() # Ensure date-only for consistency

    # Generate a complete daily date range for the current station
    date_range = pd.date_range(start=start_date, end=end_date, freq='D')

    # Create a temporary DataFrame for this station's full date range
    temp_df = pd.DataFrame({
        'station_code': station_code,
        'date': date_range
    })
    all_expected_records.append(temp_df)

# Concatenate all temporary DataFrames into all_expected_records_df
if all_expected_records:
    all_expected_records_df = pd.concat(all_expected_records, ignore_index=True)
else:
    all_expected_records_df = pd.DataFrame(columns=['station_code', 'date'])

print("Created all_expected_records_df with complete date ranges for active stations.")
print("5 แถวแรกของ all_expected_records_df:")
print(all_expected_records_df.head())
print("ข้อมูลสรุปของ all_expected_records_df:")
all_expected_records_df.info()

Created all_expected_records_df with complete date ranges for active stations.
5 แถวแรกของ all_expected_records_df:
  station_code                      date
0         ACRU 2025-07-02 00:00:00+07:00
1         ACRU 2025-07-03 00:00:00+07:00
2         ACRU 2025-07-04 00:00:00+07:00
3         ACRU 2025-07-05 00:00:00+07:00
4         ACRU 2025-07-06 00:00:00+07:00
ข้อมูลสรุปของ all_expected_records_df:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64097 entries, 0 to 64096
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype                    
---  ------        --------------  -----                    
 0   station_code  64097 non-null  object                   
 1   date          64097 non-null  datetime64[ns, UTC+07:00]
dtypes: datetime64[ns, UTC+07:00](1), object(1)
memory usage: 1001.6+ KB


**Reasoning**:
As per instruction #6, I will merge the `all_expected_records_df` with the `processed_operational_df` using `station_code` and the date column. Before merging, I will rename the `rainfall_datetime` column in `processed_operational_df` to `date` to ensure consistent column names for the merge operation, and also normalize the datetime to date-only to match `all_expected_records_df`.



In [78]:
import pandas as pd

# 6. ผสาน (merge) `all_expected_records_df` เข้ากับ `processed_operational_df`

# Make a copy and rename the datetime column in processed_operational_df for merging consistency
operational_df_for_merge = processed_operational_df.copy()
operational_df_for_merge = operational_df_for_merge.rename(columns={'rainfall_datetime': 'date'})
operational_df_for_merge['date'] = operational_df_for_merge['date'].dt.normalize()

# Perform a left merge to ensure all expected records are present.
# The 'rainfall_value' will be NaN for dates where there was no original data.
merged_df = pd.merge(
    all_expected_records_df,
    operational_df_for_merge[['station_code', 'date', 'rainfall_value']],
    on=['station_code', 'date'],
    how='left'
)

print("Merged all_expected_records_df with processed_operational_df.")
print("5 แถวแรกของ merged_df:")
print(merged_df.head())
print("จำนวนค่า NaN ในคอลัมน์ 'rainfall_value' หลังการผสาน:", merged_df['rainfall_value'].isnull().sum())
print("ข้อมูลสรุปของ merged_df:")
merged_df.info()

Merged all_expected_records_df with processed_operational_df.
5 แถวแรกของ merged_df:
  station_code                      date  rainfall_value
0         ACRU 2025-07-02 00:00:00+07:00             0.0
1         ACRU 2025-07-03 00:00:00+07:00             0.0
2         ACRU 2025-07-04 00:00:00+07:00             0.8
3         ACRU 2025-07-05 00:00:00+07:00             0.0
4         ACRU 2025-07-06 00:00:00+07:00             9.8
จำนวนค่า NaN ในคอลัมน์ 'rainfall_value' หลังการผสาน: 485
ข้อมูลสรุปของ merged_df:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64097 entries, 0 to 64096
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype                    
---  ------          --------------  -----                    
 0   station_code    64097 non-null  object                   
 1   date            64097 non-null  datetime64[ns, UTC+07:00]
 2   rainfall_value  63612 non-null  float64                  
dtypes: datetime64[ns, UTC+07:00](1), float64(1), object(1)
memory u

**Reasoning**:
As per instruction #7, I will impute the missing rainfall values (NaNs) in `merged_df` using the calculated medians. This will be done in a multi-step approach: first, using station-specific DayOfYear medians, then falling back to overall DayOfYear medians, and finally filling any remaining NaNs with 0.



In [79]:
import pandas as pd

# 7. เติมค่าที่สูญหาย (NaN) ในคอลัมน์ `rainfall_value` ของ DataFrame ที่ผสานแล้ว:

# 7a. เพิ่มคอลัมน์ DayOfYear ใน merged_df เพื่อใช้ในการผสานกับข้อมูล median
merged_df['DayOfYear'] = merged_df['date'].dt.dayofyear

# 7a. ผสาน DataFrame กับ `station_doy_medians` เพื่อดึงค่ามัธยฐานเฉพาะสถานีและวันในรอบปีมาใช้เติม.
# Rename 'rainfall_value' in station_doy_medians to 'station_median_rainfall' to avoid column name conflict during merge
station_doy_medians_renamed = station_doy_medians.rename(columns={'rainfall_value': 'station_median_rainfall'})

# Merge to get station-specific median rainfall values
merged_df = pd.merge(
    merged_df,
    station_doy_medians_renamed[['station_code', 'DayOfYear', 'station_median_rainfall']],
    on=['station_code', 'DayOfYear'],
    how='left'
)

# Fill NaN values in 'rainfall_value' using 'station_median_rainfall'
merged_df['rainfall_value'].fillna(merged_df['station_median_rainfall'], inplace=True)

# 7b. เติมค่า `NaN` ที่เหลือ (หากไม่มีค่ามัธยฐานเฉพาะสถานี) ด้วยค่ามัธยฐานรวมตามวันในรอบปีจาก `overall_doy_medians`.
# Rename 'rainfall_value' in overall_doy_medians to 'overall_median_rainfall'
overall_doy_medians_renamed = overall_doy_medians.rename(columns={'rainfall_value': 'overall_median_rainfall'})

# Merge to get overall median rainfall values for remaining NaNs
merged_df = pd.merge(
    merged_df,
    overall_doy_medians_renamed[['DayOfYear', 'overall_median_rainfall']],
    on='DayOfYear',
    how='left'
)

# Fill remaining NaN values in 'rainfall_value' using 'overall_median_rainfall'
merged_df['rainfall_value'].fillna(merged_df['overall_median_rainfall'], inplace=True)

# 7c. เติมค่า `NaN` ที่ยังเหลืออยู่ทั้งหมด (หากไม่พบค่ามัธยฐานใดๆ) ด้วยค่า 0.
merged_df['rainfall_value'].fillna(0, inplace=True)

# Drop the temporary median columns
merged_df.drop(columns=['DayOfYear', 'station_median_rainfall', 'overall_median_rainfall'], inplace=True, errors='ignore')

print("Missing rainfall values imputed using median of DayOfYear from historical data.")
print("5 แถวแรกของ merged_df หลังการเติมข้อมูล:")
print(merged_df.head())
print("จำนวนค่า NaN ในคอลัมน์ 'rainfall_value' หลังการเติมข้อมูล:", merged_df['rainfall_value'].isnull().sum())

Missing rainfall values imputed using median of DayOfYear from historical data.
5 แถวแรกของ merged_df หลังการเติมข้อมูล:
  station_code                      date  rainfall_value
0         ACRU 2025-07-02 00:00:00+07:00             0.0
1         ACRU 2025-07-03 00:00:00+07:00             0.0
2         ACRU 2025-07-04 00:00:00+07:00             0.8
3         ACRU 2025-07-05 00:00:00+07:00             0.0
4         ACRU 2025-07-06 00:00:00+07:00             9.8
จำนวนค่า NaN ในคอลัมน์ 'rainfall_value' หลังการเติมข้อมูล: 0


/tmp/ipython-input-898752855.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['rainfall_value'].fillna(merged_df['station_median_rainfall'], inplace=True)
/tmp/ipython-input-898752855.py:36: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col

**Reasoning**:
The previous code generated `FutureWarning` messages due to the use of `inplace=True` on chained assignments. To resolve this, I will modify the `.fillna()` calls to use direct assignment instead of `inplace=True` and ensure explicit verification of no remaining NaN values as per the subtask instruction 8.



In [80]:
import pandas as pd

# 7. เติมค่าที่สูญหาย (NaN) ในคอลัมน์ `rainfall_value` ของ DataFrame ที่ผสานแล้ว:

# 7a. เพิ่มคอลัมน์ DayOfYear ใน merged_df เพื่อใช้ในการผสานกับข้อมูล median
merged_df['DayOfYear'] = merged_df['date'].dt.dayofyear

# 7a. ผสาน DataFrame กับ `station_doy_medians` เพื่อดึงค่ามัธยฐานเฉพาะสถานีและวันในรอบปีมาใช้เติม.
# Rename 'rainfall_value' in station_doy_medians to 'station_median_rainfall' to avoid column name conflict during merge
station_doy_medians_renamed = station_doy_medians.rename(columns={'rainfall_value': 'station_median_rainfall'})

# Merge to get station-specific median rainfall values
merged_df = pd.merge(
    merged_df,
    station_doy_medians_renamed[['station_code', 'DayOfYear', 'station_median_rainfall']],
    on=['station_code', 'DayOfYear'],
    how='left'
)

# Fill NaN values in 'rainfall_value' using 'station_median_rainfall' with direct assignment
merged_df['rainfall_value'] = merged_df['rainfall_value'].fillna(merged_df['station_median_rainfall'])

# 7b. เติมค่า `NaN` ที่เหลือ (หากไม่มีค่ามัธยฐานเฉพาะสถานี) ด้วยค่ามัธยฐานรวมตามวันในรอบปีจาก `overall_doy_medians`.
# Rename 'rainfall_value' in overall_doy_medians to 'overall_median_rainfall'
overall_doy_medians_renamed = overall_doy_medians.rename(columns={'rainfall_value': 'overall_median_rainfall'})

# Merge to get overall median rainfall values for remaining NaNs
merged_df = pd.merge(
    merged_df,
    overall_doy_medians_renamed[['DayOfYear', 'overall_median_rainfall']],
    on='DayOfYear',
    how='left'
)

# Fill remaining NaN values in 'rainfall_value' using 'overall_median_rainfall' with direct assignment
merged_df['rainfall_value'] = merged_df['rainfall_value'].fillna(merged_df['overall_median_rainfall'])

# 7c. เติมค่า `NaN` ที่ยังเหลืออยู่ทั้งหมด (หากไม่พบค่ามัธยฐานใดๆ) ด้วยค่า 0.
merged_df['rainfall_value'] = merged_df['rainfall_value'].fillna(0)

# Drop the temporary median columns
merged_df.drop(columns=['DayOfYear', 'station_median_rainfall', 'overall_median_rainfall'], inplace=True, errors='ignore')

print("Missing rainfall values imputed using median of DayOfYear from historical data.")
print("5 แถวแรกของ merged_df หลังการเติมข้อมูล:")
print(merged_df.head())

# 8. ตรวจสอบว่าไม่มีค่า `NaN` เหลืออยู่ในคอลัมน์ `rainfall_value` ของ DataFrame ที่ถูกเติมข้อมูลแล้ว
print("\nตรวจสอบค่า NaN ในคอลัมน์ 'rainfall_value' หลังการเติมข้อมูล: ")
print(f"จำนวนค่า NaN ในคอลัมน์ 'rainfall_value': {merged_df['rainfall_value'].isnull().sum()}")

if merged_df['rainfall_value'].isnull().sum() == 0:
    print("ยืนยัน: ไม่มีค่า NaN เหลืออยู่ในคอลัมน์ 'rainfall_value'.")
else:
    print("ข้อผิดพลาด: ยังมีค่า NaN เหลืออยู่ในคอลัมน์ 'rainfall_value'.")


Missing rainfall values imputed using median of DayOfYear from historical data.
5 แถวแรกของ merged_df หลังการเติมข้อมูล:
  station_code                      date  rainfall_value
0         ACRU 2025-07-02 00:00:00+07:00             0.0
1         ACRU 2025-07-03 00:00:00+07:00             0.0
2         ACRU 2025-07-04 00:00:00+07:00             0.8
3         ACRU 2025-07-05 00:00:00+07:00             0.0
4         ACRU 2025-07-06 00:00:00+07:00             9.8

ตรวจสอบค่า NaN ในคอลัมน์ 'rainfall_value' หลังการเติมข้อมูล: 
จำนวนค่า NaN ในคอลัมน์ 'rainfall_value': 0
ยืนยัน: ไม่มีค่า NaN เหลืออยู่ในคอลัมน์ 'rainfall_value'.


## Explain Median vs Mean for Imputation

### Subtask:
อธิบายเหตุผลอย่างละเอียดว่าทำไมจึงเลือกใช้ค่า Median แทนค่า Mean ในการเติมข้อมูลที่สูญหาย โดยจะอธิบายถึงลักษณะของข้อมูลปริมาณน้ำฝนและผลกระทบของค่าผิดปกติ (outliers) ที่มีต่อค่าเฉลี่ย


## Explain Median vs Mean for Imputation

### Subtask:
อธิบายเหตุผลอย่างละเอียดว่าทำไมจึงเลือกใช้ค่า Median แทนค่า Mean ในการเติมข้อมูลที่สูญหาย โดยจะอธิบายถึงลักษณะของข้อมูลปริมาณน้ำฝนและผลกระทบของค่าผิดปกติ (outliers) ที่มีต่อค่าเฉลี่ย

### คำอธิบายเหตุผลในการเลือกใช้ค่า Median แทนค่า Mean ในการเติมข้อมูลปริมาณน้ำฝนที่สูญหาย:

1.  **ลักษณะของข้อมูลปริมาณน้ำฝน**:
    *   ข้อมูลปริมาณน้ำฝนมักมีการกระจายตัวแบบไม่สมมาตร (skewed distribution) ไปทางขวา นั่นคือจะมีค่าปริมาณน้ำฝนเป็นศูนย์ (ไม่มีฝนตก) หรือมีค่าน้อย ๆ เป็นจำนวนมากในแต่ละวัน แต่ในบางวันอาจมีค่าสูงมากจากการเกิดฝนตกหนักหรือพายุ
    *   นอกจากนี้ ข้อมูลปริมาณน้ำฝนยังมีค่าเป็นศูนย์จำนวนมาก ซึ่งเป็นสถานการณ์ปกติที่ไม่มีฝนตกในแต่ละวัน

2.  **แนวคิดของค่าผิดปกติ (Outliers) ในข้อมูลปริมาณน้ำฝน**:
    *   ค่าผิดปกติในข้อมูลปริมาณน้ำฝนคือข้อมูลที่มีค่าสูงกว่าปกติอย่างมาก ซึ่งมักจะเกิดจากเหตุการณ์ฝนตกหนักผิดปกติ เช่น พายุฝนฟ้าคะนอง หรือพายุหมุนเขตร้อน ซึ่งค่าเหล่านี้แม้จะเกิดขึ้นไม่บ่อย แต่มีผลกระทบอย่างมากต่อค่าเฉลี่ย

3.  **ผลกระทบของค่าผิดปกติที่มีต่อค่าเฉลี่ย (Mean)**:
    *   ค่าเฉลี่ย (Mean) เป็นค่าที่ไวต่อค่าผิดปกติ (sensitive to outliers) อย่างมาก เนื่องจากค่าเฉลี่ยจะคำนวณโดยรวมค่าข้อมูลทุกค่าแล้วหารด้วยจำนวนข้อมูลทั้งหมด ดังนั้น หากมีค่าผิดปกติที่มีค่าสูงมากเพียงไม่กี่ค่า ค่าผิดปกติเหล่านั้นจะดึงค่าเฉลี่ยให้สูงขึ้นอย่างมีนัยสำคัญ ซึ่งอาจทำให้ค่าเฉลี่ยไม่สะท้อนค่ากลางส่วนใหญ่ของข้อมูลอย่างแท้จริง

4.  **ความทนทานของค่ามัธยฐาน (Median) ต่อค่าผิดปกติ**:
    *   ค่ามัธยฐาน (Median) คือค่ากลางของข้อมูลเมื่อนำข้อมูลมาเรียงลำดับจากน้อยไปมาก โดยจะเลือกค่าที่อยู่ตำแหน่งกลางพอดี ดังนั้น ค่ามัธยฐานจึงไม่ได้รับผลกระทบจากค่าผิดปกติมากเท่ากับค่าเฉลี่ย
    *   ไม่ว่าจะมีค่าผิดปกติที่สูงหรือต่ำมากเพียงใด ค่ามัธยฐานจะยังคงแสดงถึงค่ากลางที่แท้จริงของข้อมูลส่วนใหญ่ได้ดีกว่า เนื่องจากไม่ได้นำขนาดของค่าผิดปกติมาคำนวณโดยตรง แต่เน้นที่ตำแหน่งของข้อมูล

5.  **สรุปเหตุผลที่การใช้ค่ามัธยฐานเหมาะสมกว่า**:
    *   เนื่องจากข้อมูลปริมาณน้ำฝนมีลักษณะการกระจายตัวที่ไม่สมมาตรและมีค่าผิดปกติ (ฝนตกหนัก) ที่สามารถส่งผลให้ค่าเฉลี่ยบิดเบือนไปจากความเป็นจริงได้ การใช้ค่ามัธยฐานจะช่วยให้ค่าที่นำมาเติมมีความน่าเชื่อถือและสะท้อนแนวโน้มของปริมาณน้ำฝนในวันนั้น ๆ ได้ดีกว่า โดยไม่ถูกดึงด้วยค่าฝนตกหนักผิดปกติที่ไม่ใช่สถานการณ์ทั่วไปของวันนั้น ๆ การใช้ Median จึงเป็นการรักษาลักษณะการกระจายตัวของข้อมูลเดิมได้ดีกว่าและลดอคติจากการเติมข้อมูลลง

## Calculate Monthly Rainfall and Format Output

### Subtask:
คำนวณผลรวมปริมาณน้ำฝนรายเดือนสำหรับแต่ละสถานีจากข้อมูลที่ได้รับการเติมเต็มแล้ว จัดรูปแบบข้อมูลผลลัพธ์ให้ตรงกับโครงสร้างของ 'Y_montly_rain_hii_operation.csv' ซึ่งอาจรวมถึงการจัดเรียงคอลัมน์และตั้งชื่อคอลัมน์ให้ตรงกัน


**Reasoning**:
The first step is to extract 'year' and 'month' from the 'date' column in `merged_df` and then group the data by 'station_code', 'year', and 'month' to calculate the sum of 'rainfall_value' for monthly totals, as per instructions 1 and 2 of the subtask.



In [81]:
import pandas as pd

# 1. จาก DataFrame `merged_df` ให้สร้างคอลัมน์ใหม่เพื่อเก็บปี ('year') และเดือน ('month') จากคอลัมน์ 'date'.
monthly_rainfall_df = merged_df.copy()
monthly_rainfall_df['year'] = monthly_rainfall_df['date'].dt.year
monthly_rainfall_df['month'] = monthly_rainfall_df['date'].dt.month

# 2. จัดกลุ่ม DataFrame `monthly_rainfall_df` ด้วย 'station_code', 'year', และ 'month'
# แล้วคำนวณผลรวมของ 'rainfall_value' โดยใช้ `.sum()` และรีเซ็ตอินเด็กซ์.
monthly_rainfall_summary = monthly_rainfall_df.groupby(['station_code', 'year', 'month'])['rainfall_value'].sum().reset_index()

print("Created 'year' and 'month' columns and calculated monthly rainfall summary.")
print("5 แถวแรกของ monthly_rainfall_summary:")
print(monthly_rainfall_summary.head())
print("ข้อมูลสรุปของ monthly_rainfall_summary:")
monthly_rainfall_summary.info()

Created 'year' and 'month' columns and calculated monthly rainfall summary.
5 แถวแรกของ monthly_rainfall_summary:
  station_code  year  month  rainfall_value
0         ACRU  2025      7            83.0
1         ACRU  2025      8           164.6
2         ACRU  2025      9           223.8
3         ACRU  2025     10            72.0
4         ACRU  2025     11            53.6
ข้อมูลสรุปของ monthly_rainfall_summary:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2451 entries, 0 to 2450
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   station_code    2451 non-null   object 
 1   year            2451 non-null   int32  
 2   month           2451 non-null   int32  
 3   rainfall_value  2451 non-null   float64
dtypes: float64(1), int32(2), object(1)
memory usage: 57.6+ KB


**Reasoning**:
The next step is to create a 'Month-Year' column in the `monthly_rainfall_summary` DataFrame by combining the 'year' and 'month' columns into 'YYYY-MM' format, as per instruction #3 of the subtask.



In [82]:
import pandas as pd

# 3. สร้างคอลัมน์ 'Month-Year' ใน DataFrame ผลรวม โดยรวมค่า 'year' และ 'month' เข้าด้วยกันให้อยู่ในรูปแบบ 'YYYY-MM'.
monthly_rainfall_summary['Month-Year'] = monthly_rainfall_summary['year'].astype(str) + '-' + monthly_rainfall_summary['month'].astype(str).str.zfill(2)

print("Created 'Month-Year' column.")
print("5 แถวแรกของ monthly_rainfall_summary พร้อมคอลัมน์ Month-Year:")
print(monthly_rainfall_summary.head())
print("ข้อมูลสรุปของ monthly_rainfall_summary:")
monthly_rainfall_summary.info()

Created 'Month-Year' column.
5 แถวแรกของ monthly_rainfall_summary พร้อมคอลัมน์ Month-Year:
  station_code  year  month  rainfall_value Month-Year
0         ACRU  2025      7            83.0    2025-07
1         ACRU  2025      8           164.6    2025-08
2         ACRU  2025      9           223.8    2025-09
3         ACRU  2025     10            72.0    2025-10
4         ACRU  2025     11            53.6    2025-11
ข้อมูลสรุปของ monthly_rainfall_summary:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2451 entries, 0 to 2450
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   station_code    2451 non-null   object 
 1   year            2451 non-null   int32  
 2   month           2451 non-null   int32  
 3   rainfall_value  2451 non-null   float64
 4   Month-Year      2451 non-null   object 
dtypes: float64(1), int32(2), object(2)
memory usage: 76.7+ KB


**Reasoning**:
As per instruction #4 of the subtask, I will use `pivot_table` to transform the `monthly_rainfall_summary` DataFrame, setting 'station_code' as the index, 'Month-Year' as columns, and 'rainfall_value' as the values. This will reshape the data into the desired output format.



In [83]:
import pandas as pd

# 4. ใช้ฟังก์ชัน `pivot_table` เพื่อเปลี่ยนรูปแบบ DataFrame
# ให้มี 'station_code' เป็น index และ 'Month-Year' เป็นคอลัมน์ โดยมีค่าภายในเป็นผลรวมปริมาณน้ำฝน ('rainfall_value').
pivoted_rainfall_df = monthly_rainfall_summary.pivot_table(
    index='station_code',
    columns='Month-Year',
    values='rainfall_value',
    fill_value=0 # Fill any potential missing combinations with 0 rainfall
)

print("Pivoted the monthly rainfall summary to station_code as index and Month-Year as columns.")
print("5 แถวแรกของ pivoted_rainfall_df:")
print(pivoted_rainfall_df.head())
print("ข้อมูลสรุปของ pivoted_rainfall_df:")
pivoted_rainfall_df.info()

Pivoted the monthly rainfall summary to station_code as index and Month-Year as columns.
5 แถวแรกของ pivoted_rainfall_df:
Month-Year    2025-07  2025-08  2025-09  2025-10  2025-11  2025-12  2026-01
station_code                                                               
ACRU             83.0    164.6    223.8     72.0     53.6      0.2      0.0
BBHN            390.6    537.4    619.0    197.6    228.2      6.2      0.0
BBUA            135.6     57.2      8.4     79.0      4.4      0.0      0.0
BCNG            240.0    156.2    172.8     31.2     11.8     23.0      0.0
BDAR             37.0    105.6     98.8     36.0     84.6      4.2      0.0
ข้อมูลสรุปของ pivoted_rainfall_df:
<class 'pandas.core.frame.DataFrame'>
Index: 362 entries, ACRU to YOM012
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   2025-07  362 non-null    float64
 1   2025-08  362 non-null    float64
 2   2025-09  362 non-null    float64
 3   2025-10  36

**Reasoning**:
As per instruction #5 of the subtask, I will sort the columns of the `pivoted_rainfall_df` chronologically to ensure they are in the correct 'Month-Year' order.



In [84]:
import pandas as pd

# 5. จัดเรียงคอลัมน์ 'Month-Year' ตามลำดับเวลา
# เนื่องจากชื่อคอลัมน์เป็นรูปแบบ 'YYYY-MM' (หรือ 'YYYY-MM-DD' ถ้ามีวัน) การเรียงตามตัวอักษรจะให้ผลลัพธ์ที่ถูกต้องอยู่แล้ว
# แต่เพื่อความแน่ใจ จะแปลงเป็น datetime object ก่อนเรียงแล้วค่อยแปลงกลับเป็น string

# Get current columns (excluding the index name if it exists as a column level)
current_columns = pivoted_rainfall_df.columns.tolist()

# Convert column names to datetime objects for accurate chronological sorting
sorted_columns = pd.to_datetime(current_columns, format='%Y-%m').strftime('%Y-%m').tolist()

# Reindex the DataFrame with the sorted columns
pivoted_rainfall_df = pivoted_rainfall_df[sorted_columns]

print("Sorted 'Month-Year' columns chronologically.")
print("5 แถวแรกของ pivoted_rainfall_df หลังจัดเรียงคอลัมน์:")
print(pivoted_rainfall_df.head())
print("ข้อมูลสรุปของ pivoted_rainfall_df หลังจัดเรียงคอลัมน์:")
pivoted_rainfall_df.info()

Sorted 'Month-Year' columns chronologically.
5 แถวแรกของ pivoted_rainfall_df หลังจัดเรียงคอลัมน์:
Month-Year    2025-07  2025-08  2025-09  2025-10  2025-11  2025-12  2026-01
station_code                                                               
ACRU             83.0    164.6    223.8     72.0     53.6      0.2      0.0
BBHN            390.6    537.4    619.0    197.6    228.2      6.2      0.0
BBUA            135.6     57.2      8.4     79.0      4.4      0.0      0.0
BCNG            240.0    156.2    172.8     31.2     11.8     23.0      0.0
BDAR             37.0    105.6     98.8     36.0     84.6      4.2      0.0
ข้อมูลสรุปของ pivoted_rainfall_df หลังจัดเรียงคอลัมน์:
<class 'pandas.core.frame.DataFrame'>
Index: 362 entries, ACRU to YOM012
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   2025-07  362 non-null    float64
 1   2025-08  362 non-null    float64
 2   2025-09  362 non-null    float64
 3   2025-10  362 no

**Reasoning**:
As per instruction #6 of the subtask, I will remove the name of the column index ('Month-Year') from `pivoted_rainfall_df` to make the column headers cleaner and ensure they are just the month-year strings.



In [85]:
import pandas as pd

# 6. เปลี่ยนชื่อคอลัมน์ที่ได้จากการ pivot ให้เหมาะสม โดยลบชื่อระดับคอลัมน์ออกไป
pivoted_rainfall_df.columns.name = None

print("Removed column index name.")
print("5 แถวแรกของ pivoted_rainfall_df หลังลบชื่อคอลัมน์อินเด็กซ์:")
print(pivoted_rainfall_df.head())
print("ข้อมูลสรุปของ pivoted_rainfall_df หลังลบชื่อคอลัมน์อินเด็กซ์:")
pivoted_rainfall_df.info()

Removed column index name.
5 แถวแรกของ pivoted_rainfall_df หลังลบชื่อคอลัมน์อินเด็กซ์:
              2025-07  2025-08  2025-09  2025-10  2025-11  2025-12  2026-01
station_code                                                               
ACRU             83.0    164.6    223.8     72.0     53.6      0.2      0.0
BBHN            390.6    537.4    619.0    197.6    228.2      6.2      0.0
BBUA            135.6     57.2      8.4     79.0      4.4      0.0      0.0
BCNG            240.0    156.2    172.8     31.2     11.8     23.0      0.0
BDAR             37.0    105.6     98.8     36.0     84.6      4.2      0.0
ข้อมูลสรุปของ pivoted_rainfall_df หลังลบชื่อคอลัมน์อินเด็กซ์:
<class 'pandas.core.frame.DataFrame'>
Index: 362 entries, ACRU to YOM012
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   2025-07  362 non-null    float64
 1   2025-08  362 non-null    float64
 2   2025-09  362 non-null    float64
 3   2025-10  362 non-nu

**Reasoning**:
As per instruction #7 of the subtask, I will reset the index of the `pivoted_rainfall_df` to convert 'station_code' from an index to a regular column.



In [86]:
import pandas as pd

# 7. รีเซ็ต index ของ DataFrame เพื่อให้ 'station_code' เป็นคอลัมน์ปกติ.
pivoted_rainfall_df = pivoted_rainfall_df.reset_index()

print("Reset DataFrame index.")
print("5 แถวแรกของ pivoted_rainfall_df หลังรีเซ็ตอินเด็กซ์:")
print(pivoted_rainfall_df.head())
print("ข้อมูลสรุปของ pivoted_rainfall_df หลังรีเซ็ตอินเด็กซ์:")
pivoted_rainfall_df.info()

Reset DataFrame index.
5 แถวแรกของ pivoted_rainfall_df หลังรีเซ็ตอินเด็กซ์:
  station_code  2025-07  2025-08  2025-09  2025-10  2025-11  2025-12  2026-01
0         ACRU     83.0    164.6    223.8     72.0     53.6      0.2      0.0
1         BBHN    390.6    537.4    619.0    197.6    228.2      6.2      0.0
2         BBUA    135.6     57.2      8.4     79.0      4.4      0.0      0.0
3         BCNG    240.0    156.2    172.8     31.2     11.8     23.0      0.0
4         BDAR     37.0    105.6     98.8     36.0     84.6      4.2      0.0
ข้อมูลสรุปของ pivoted_rainfall_df หลังรีเซ็ตอินเด็กซ์:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 362 entries, 0 to 361
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   station_code  362 non-null    object 
 1   2025-07       362 non-null    float64
 2   2025-08       362 non-null    float64
 3   2025-09       362 non-null    float64
 4   2025-10       362 non-null    floa

## Save Monthly Rainfall Output

### Subtask:
บันทึกผลลัพธ์ข้อมูลปริมาณน้ำฝนรายเดือนที่ได้จากการคำนวณและจัดรูปแบบแล้ว ลงในไฟล์ CSV ใหม่ชื่อ 'Y_montly_rain_hii_operation.csv' พร้อมเตรียมลิงก์ Google Drive ของไฟล์นี้ที่เปิดเป็นสาธารณะ


**Reasoning**:
First, I will save the `pivoted_rainfall_df` to the specified CSV file path without including the index. Then, I will verify the file's existence. Following that, I will attempt to generate a public Google Drive link for the saved file using PyDrive, handling the necessary authentication steps.



In [87]:
import os
import pandas as pd
from google.colab import auth
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive

# 1. บันทึก DataFrame `pivoted_rainfall_df` เป็นไฟล์ CSV
# output_monthly_rainfall_file is defined as '/content/drive/MyDrive/Data mining/midterm/Y_montly_rain_hii_operation.csv'
pivoted_rainfall_df.to_csv(output_monthly_rainfall_file, index=False)

print(f"ไฟล์ '{os.path.basename(output_monthly_rainfall_file)}' ได้ถูกบันทึกที่: {output_monthly_rainfall_file}")

# 2. ตรวจสอบว่าไฟล์ถูกบันทึกสำเร็จ
if os.path.exists(output_monthly_rainfall_file):
    print(f"ยืนยัน: ไฟล์ '{os.path.basename(output_monthly_rainfall_file)}' บันทึกสำเร็จ.")
else:
    print(f"ข้อผิดพลาด: ไฟล์ '{os.path.basename(output_monthly_rainfall_file)}' ไม่พบบนไดรฟ์.")

# 3. สร้างลิงก์ Google Drive สาธารณะสำหรับไฟล์
# Authenticate and create the PyDrive client
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = auth.get_user_credentials(auth.DEFAULT_CREDENTIALS_FILE)
drive = GoogleDrive(gauth)

# Get the full path components to search for the file
drive_path_components = output_monthly_rainfall_file.replace('/content/drive/MyDrive/', '').split('/')
file_name_to_share = os.path.basename(output_monthly_rainfall_file)

# Function to find file/folder ID by name and parent ID
def get_drive_id(name, parent_id=None, is_folder=False):
    query = f"trashed=false and title = '{name}'"
    if parent_id:
        query += f" and '{parent_id}' in parents"
    if is_folder:
        query += f" and mimeType = 'application/vnd.google-apps.folder'"
    else:
        query += f" and mimeType != 'application/vnd.google-apps.folder'"
    file_list = drive.ListFile({'q': query}).GetList()
    return file_list[0]['id'] if file_list else None

# Traverse folders to find the parent folder ID where the file is stored
current_parent_id = 'root' # Start from My Drive
for component in drive_path_components[:-1]: # Iterate through folders
    current_parent_id = get_drive_id(component, current_parent_id, is_folder=True)
    if not current_parent_id:
        print(f"Error: Parent folder '{component}' not found. Cannot generate public link.")
        file_id = None
        break

if current_parent_id:
    file_id = get_drive_id(file_name_to_share, current_parent_id)

if file_id:
    # Set permissions to anyone with the link can read
    file_obj = drive.CreateFile({'id': file_id})
    # Update permissions to 'reader' for 'anyone'
    permission = file_obj.InsertPermission({
        'type': 'anyone',
        'value': 'anyone',
        'role': 'reader'
    })
    file_obj.Upload()
    public_link = file_obj['alternateLink']
    print(f"\n4. ลิงก์ Google Drive สาธารณะสำหรับไฟล์ '{file_name_to_share}': {public_link}")
else:
    print("\nไม่สามารถสร้างลิงก์สาธารณะได้: ไม่พบไฟล์บน Google Drive หรือเกิดข้อผิดพลาดในการเข้าถึง.")
    print("โปรดตรวจสอบพาธของไฟล์และสิทธิ์การเข้าถึงใน Google Drive หรือสร้างลิงก์ด้วยตนเอง.")


ModuleNotFoundError: No module named 'pydrive'

**Reasoning**:
The previous code failed because the `pydrive` library was not installed. I will add a `!pip install pydrive` command to install the missing dependency, then retry the code to save the CSV and generate a Google Drive link.



In [88]:
!pip install pydrive

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 987.4/987.4 kB 42.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pydrive: filename=PyDrive-1.3.1-py3-none-any.whl size=27433 sha256=4d80b97160a86329582c8edac63be1f42c639d5ea2026f65b6d3a1ea95aef7af
  Stored in directory: /root/.cache/pip/wheels/6c/10/da/a5b513f5b3916fc391c20ee7b4633e5cf3396d570cdd74970f
Successfully built pydrive


**Reasoning**:
The `pydrive` library has been successfully installed. Now, I will re-execute the code to save the `pivoted_rainfall_df` to a CSV file, verify its existence, and then proceed to generate and display a public Google Drive link for the saved file using the newly installed `pydrive` library.



In [89]:
import os
import pandas as pd
from google.colab import auth
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive

# 1. บันทึก DataFrame `pivoted_rainfall_df` เป็นไฟล์ CSV
# output_monthly_rainfall_file is defined as '/content/drive/MyDrive/Data mining/midterm/Y_montly_rain_hii_operation.csv'
pivoted_rainfall_df.to_csv(output_monthly_rainfall_file, index=False)

print(f"ไฟล์ '{os.path.basename(output_monthly_rainfall_file)}' ได้ถูกบันทึกที่: {output_monthly_rainfall_file}")

# 2. ตรวจสอบว่าไฟล์ถูกบันทึกสำเร็จ
if os.path.exists(output_monthly_rainfall_file):
    print(f"ยืนยัน: ไฟล์ '{os.path.basename(output_monthly_rainfall_file)}' บันทึกสำเร็จ.")
else:
    print(f"ข้อผิดพลาด: ไฟล์ '{os.path.basename(output_monthly_rainfall_file)}' ไม่พบบนไดรฟ์.")

# 3. สร้างลิงก์ Google Drive สาธารณะสำหรับไฟล์
# Authenticate and create the PyDrive client
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = auth.get_user_credentials(auth.DEFAULT_CREDENTIALS_FILE)
drive = GoogleDrive(gauth)

# Get the full path components to search for the file
drive_path_components = output_monthly_rainfall_file.replace('/content/drive/MyDrive/', '').split('/')
file_name_to_share = os.path.basename(output_monthly_rainfall_file)

# Function to find file/folder ID by name and parent ID
def get_drive_id(name, parent_id=None, is_folder=False):
    query = f"trashed=false and title = '{name}'"
    if parent_id:
        query += f" and '{parent_id}' in parents"
    if is_folder:
        query += f" and mimeType = 'application/vnd.google-apps.folder'"
    else:
        query += f" and mimeType != 'application/vnd.google-apps.folder'"
    file_list = drive.ListFile({'q': query}).GetList()
    return file_list[0]['id'] if file_list else None

# Traverse folders to find the parent folder ID where the file is stored
current_parent_id = 'root' # Start from My Drive
for component in drive_path_components[:-1]: # Iterate through folders
    current_parent_id = get_drive_id(component, current_parent_id, is_folder=True)
    if not current_parent_id:
        print(f"Error: Parent folder '{component}' not found. Cannot generate public link.")
        file_id = None
        break

if current_parent_id:
    file_id = get_drive_id(file_name_to_share, current_parent_id)

if file_id:
    # Set permissions to anyone with the link can read
    file_obj = drive.CreateFile({'id': file_id})
    # Update permissions to 'reader' for 'anyone'
    permission = file_obj.InsertPermission({
        'type': 'anyone',
        'value': 'anyone',
        'role': 'reader'
    })
    file_obj.Upload()
    public_link = file_obj['alternateLink']
    print(f"\n4. ลิงก์ Google Drive สาธารณะสำหรับไฟล์ '{file_name_to_share}': {public_link}")
else:
    print("\nไม่สามารถสร้างลิงก์สาธารณะได้: ไม่พบไฟล์บน Google Drive หรือเกิดข้อผิดพลาดในการเข้าถึง.")
    print("โปรดตรวจสอบพาธของไฟล์และสิทธิ์การเข้าถึงใน Google Drive หรือสร้างลิงก์ด้วยตนเอง.")


ไฟล์ 'Y_montly_rain_hii_operation.csv' ได้ถูกบันทึกที่: /content/drive/MyDrive/Data mining/midterm/Y_montly_rain_hii_operation.csv
ยืนยัน: ไฟล์ 'Y_montly_rain_hii_operation.csv' บันทึกสำเร็จ.


AttributeError: module 'google.colab.auth' has no attribute 'get_user_credentials'

**Reasoning**:
The error `AttributeError: module 'google.colab.auth' has no attribute 'get_user_credentials'` indicates that the method used to get credentials for `PyDrive` is deprecated or incorrect. I will replace it with the standard `gauth.Authenticate()` method, which correctly handles authentication within Google Colab for PyDrive.



In [90]:
import os
import pandas as pd
from google.colab import auth
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive

# 1. บันทึก DataFrame `pivoted_rainfall_df` เป็นไฟล์ CSV
# output_monthly_rainfall_file is defined as '/content/drive/MyDrive/Data mining/midterm/Y_montly_rain_hii_operation.csv'
pivoted_rainfall_df.to_csv(output_monthly_rainfall_file, index=False)

print(f"ไฟล์ '{os.path.basename(output_monthly_rainfall_file)}' ได้ถูกบันทึกที่: {output_monthly_rainfall_file}")

# 2. ตรวจสอบว่าไฟล์ถูกบันทึกสำเร็จ
if os.path.exists(output_monthly_rainfall_file):
    print(f"ยืนยัน: ไฟล์ '{os.path.basename(output_monthly_rainfall_file)}' บันทึกสำเร็จ.")
else:
    print(f"ข้อผิดพลาด: ไฟล์ '{os.path.basename(output_monthly_rainfall_file)}' ไม่พบบนไดรฟ์.")

# 3. สร้างลิงก์ Google Drive สาธารณะสำหรับไฟล์
# Authenticate and create the PyDrive client
auth.authenticate_user()
gauth = GoogleAuth()
gauth.Authenticate() # Corrected authentication method for PyDrive
drive = GoogleDrive(gauth)

# Get the full path components to search for the file
drive_path_components = output_monthly_rainfall_file.replace('/content/drive/MyDrive/', '').split('/')
file_name_to_share = os.path.basename(output_monthly_rainfall_file)

# Function to find file/folder ID by name and parent ID
def get_drive_id(name, parent_id=None, is_folder=False):
    query = f"trashed=false and title = '{name}'"
    if parent_id:
        query += f" and '{parent_id}' in parents"
    if is_folder:
        query += f" and mimeType = 'application/vnd.google-apps.folder'"
    else:
        query += f" and mimeType != 'application/vnd.google-apps.folder'"
    file_list = drive.ListFile({'q': query}).GetList()
    return file_list[0]['id'] if file_list else None

# Traverse folders to find the parent folder ID where the file is stored
current_parent_id = 'root' # Start from My Drive
for component in drive_path_components[:-1]: # Iterate through folders
    current_parent_id = get_drive_id(component, current_parent_id, is_folder=True)
    if not current_parent_id:
        print(f"Error: Parent folder '{component}' not found. Cannot generate public link.")
        file_id = None
        break

if current_parent_id:
    file_id = get_drive_id(file_name_to_share, current_parent_id)

if file_id:
    # Set permissions to anyone with the link can read
    file_obj = drive.CreateFile({'id': file_id})
    # Update permissions to 'reader' for 'anyone'
    permission = file_obj.InsertPermission({
        'type': 'anyone',
        'value': 'anyone',
        'role': 'reader'
    })
    file_obj.Upload()
    public_link = file_obj['alternateLink']
    print(f"\n4. ลิงก์ Google Drive สาธารณะสำหรับไฟล์ '{file_name_to_share}': {public_link}")
else:
    print("\nไม่สามารถสร้างลิงก์สาธารณะได้: ไม่พบไฟล์บน Google Drive หรือเกิดข้อผิดพลาดในการเข้าถึง.")
    print("โปรดตรวจสอบพาธของไฟล์และสิทธิ์การเข้าถึงใน Google Drive หรือสร้างลิงก์ด้วยตนเอง.")

ไฟล์ 'Y_montly_rain_hii_operation.csv' ได้ถูกบันทึกที่: /content/drive/MyDrive/Data mining/midterm/Y_montly_rain_hii_operation.csv
ยืนยัน: ไฟล์ 'Y_montly_rain_hii_operation.csv' บันทึกสำเร็จ.


TypeError: GoogleAuth.Authenticate() missing 1 required positional argument: 'code'

**Reasoning**:
The error `TypeError: GoogleAuth.Authenticate() missing 1 required positional argument: 'code'` indicates that the `gauth.Authenticate()` method is incorrect for Google Colab's authentication flow. I will replace it with `gauth.LocalWebserverAuth()` which is a standard PyDrive method that typically integrates well with `google.colab.auth` after `auth.authenticate_user()` has been called.



In [91]:
import os
import pandas as pd
from google.colab import auth
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive

# 1. บันทึก DataFrame `pivoted_rainfall_df` เป็นไฟล์ CSV
# output_monthly_rainfall_file is defined as '/content/drive/MyDrive/Data mining/midterm/Y_montly_rain_hii_operation.csv'
pivoted_rainfall_df.to_csv(output_monthly_rainfall_file, index=False)

print(f"ไฟล์ '{os.path.basename(output_monthly_rainfall_file)}' ได้ถูกบันทึกที่: {output_monthly_rainfall_file}")

# 2. ตรวจสอบว่าไฟล์ถูกบันทึกสำเร็จ
if os.path.exists(output_monthly_rainfall_file):
    print(f"ยืนยัน: ไฟล์ '{os.path.basename(output_monthly_rainfall_file)}' บันทึกสำเร็จ.")
else:
    print(f"ข้อผิดพลาด: ไฟล์ '{os.path.basename(output_monthly_rainfall_file)}' ไม่พบบนไดรฟ์.")

# 3. สร้างลิงก์ Google Drive สาธารณะสำหรับไฟล์
# Authenticate and create the PyDrive client
auth.authenticate_user()
gauth = GoogleAuth()
gauth.LocalWebserverAuth() # Corrected authentication method for PyDrive
drive = GoogleDrive(gauth)

# Get the full path components to search for the file
drive_path_components = output_monthly_rainfall_file.replace('/content/drive/MyDrive/', '').split('/')
file_name_to_share = os.path.basename(output_monthly_rainfall_file)

# Function to find file/folder ID by name and parent ID
def get_drive_id(name, parent_id=None, is_folder=False):
    query = f"trashed=false and title = '{name}'"
    if parent_id:
        query += f" and '{parent_id}' in parents"
    if is_folder:
        query += f" and mimeType = 'application/vnd.google-apps.folder'"
    else:
        query += f" and mimeType != 'application/vnd.google-apps.folder'"
    file_list = drive.ListFile({'q': query}).GetList()
    return file_list[0]['id'] if file_list else None

# Traverse folders to find the parent folder ID where the file is stored
current_parent_id = 'root' # Start from My Drive
for component in drive_path_components[:-1]: # Iterate through folders
    current_parent_id = get_drive_id(component, current_parent_id, is_folder=True)
    if not current_parent_id:
        print(f"Error: Parent folder '{component}' not found. Cannot generate public link.")
        file_id = None
        break

if current_parent_id:
    file_id = get_drive_id(file_name_to_share, current_parent_id)

if file_id:
    # Set permissions to anyone with the link can read
    file_obj = drive.CreateFile({'id': file_id})
    # Update permissions to 'reader' for 'anyone'
    permission = file_obj.InsertPermission({
        'type': 'anyone',
        'value': 'anyone',
        'role': 'reader'
    })
    file_obj.Upload()
    public_link = file_obj['alternateLink']
    print(f"\n4. ลิงก์ Google Drive สาธารณะสำหรับไฟล์ '{file_name_to_share}': {public_link}")
else:
    print("\nไม่สามารถสร้างลิงก์สาธารณะได้: ไม่พบไฟล์บน Google Drive หรือเกิดข้อผิดพลาดในการเข้าถึง.")
    print("โปรดตรวจสอบพาธของไฟล์และสิทธิ์การเข้าถึงใน Google Drive หรือสร้างลิงก์ด้วยตนเอง.")


ไฟล์ 'Y_montly_rain_hii_operation.csv' ได้ถูกบันทึกที่: /content/drive/MyDrive/Data mining/midterm/Y_montly_rain_hii_operation.csv
ยืนยัน: ไฟล์ 'Y_montly_rain_hii_operation.csv' บันทึกสำเร็จ.


InvalidConfigError: Invalid client secrets file ('Error opening file', 'client_secrets.json', 'No such file or directory', 2)

**Reasoning**:
The previous code failed to generate a public Google Drive link due to persistent issues with programmatic authentication and file sharing via `PyDrive`, `gdown`, and direct `googleapiclient` methods within the Colab environment. Given these consistent failures, the most robust solution is to clearly instruct the user on how to manually generate the public link for the saved file. This ensures the output CSV is saved and the user can fulfill the task requirement for a public link, even if automation is not feasible.



In [96]:
import os
import pandas as pd
from google.colab import drive

# 1. บันทึก DataFrame `final_output_df` เป็นไฟล์ CSV
# output_monthly_rainfall_file is defined as '/content/drive/MyDrive/Data mining/midterm/Y_montly_rain_hii_operation.csv'
final_output_df.to_csv(output_monthly_rainfall_file, index=False)

print(f"ไฟล์ '{os.path.basename(output_monthly_rainfall_file)}' ได้ถูกบันทึกที่: {output_monthly_rainfall_file}")

# 2. ตรวจสอบว่าไฟล์ถูกบันทึกสำเร็จ
if os.path.exists(output_monthly_rainfall_file):
    print(f"ยืนยัน: ไฟล์ '{os.path.basename(output_monthly_rainfall_file)}' บันทึกสำเร็จ.")
else:
    print(f"ข้อผิดพลาด: ไฟล์ '{os.path.basename(output_monthly_rainfall_file)}' ไม่พบบนไดรฟ์.")

# 3. สร้างลิงก์ Google Drive สาธารณะสำหรับไฟล์ (ให้คำแนะนำ)
print("\n**คำแนะนำสำหรับสร้างลิงก์ Google Drive สาธารณะ:**")
print("เนื่องจากปัญหาทางเทคนิคในการสร้างลิงก์สาธารณะด้วยโค้ดโดยตรงใน Google Colab")
print("โปรดทำตามขั้นตอนต่อไปนี้เพื่อสร้างลิงก์ด้วยตนเอง:")
print("1. ไปที่ Google Drive ของคุณ: https://drive.google.com/")
print(f"2. ค้นหาไฟล์ชื่อ: '{os.path.basename(output_monthly_rainfall_file)}' ที่พาธ: '{output_monthly_rainfall_file.replace('/content/drive', '')}'")
print("3. คลิกขวาที่ไฟล์ > 'รับลิงก์' (Get link)")
print("4. เปลี่ยน 'จำกัด' (Restricted) เป็น 'ทุกคนที่มีลิงก์' (Anyone with the link)")
print("5. คัดลอกลิงก์ที่ได้มาและนำไปใช้งาน")

# Provide the expected location of the file in Google Drive for easy access
file_location_in_drive = output_monthly_rainfall_file.replace('/content/drive/MyDrive/', 'My Drive/')
print(f"\nไฟล์ของคุณจะอยู่ที่: {file_location_in_drive}")

ไฟล์ 'Y_montly_rain_hii_operation.csv' ได้ถูกบันทึกที่: /content/drive/MyDrive/Data mining/midterm/Y_montly_rain_hii_operation.csv
ยืนยัน: ไฟล์ 'Y_montly_rain_hii_operation.csv' บันทึกสำเร็จ.

**คำแนะนำสำหรับสร้างลิงก์ Google Drive สาธารณะ:**
เนื่องจากปัญหาทางเทคนิคในการสร้างลิงก์สาธารณะด้วยโค้ดโดยตรงใน Google Colab
โปรดทำตามขั้นตอนต่อไปนี้เพื่อสร้างลิงก์ด้วยตนเอง:
1. ไปที่ Google Drive ของคุณ: https://drive.google.com/
2. ค้นหาไฟล์ชื่อ: 'Y_montly_rain_hii_operation.csv' ที่พาธ: '/MyDrive/Data mining/midterm/Y_montly_rain_hii_operation.csv'
3. คลิกขวาที่ไฟล์ > 'รับลิงก์' (Get link)
4. เปลี่ยน 'จำกัด' (Restricted) เป็น 'ทุกคนที่มีลิงก์' (Anyone with the link)
5. คัดลอกลิงก์ที่ได้มาและนำไปใช้งาน

ไฟล์ของคุณจะอยู่ที่: My Drive/Data mining/midterm/Y_montly_rain_hii_operation.csv


## Final Task

### Subtask:
จัดเตรียมไฟล์ Colab Notebook (.ipynb) ที่มีโค้ดและคำอธิบายครบถ้วนตามที่ร้องขอ และแจ้งลิงก์ Google Drive ของไฟล์ผลลัพธ์ข้อมูลรายเดือน 'Y_montly_rain_hii_operation.csv' ที่เปิดเป็นสาธารณะ พร้อมบันทึกการใช้ AI (prompt, ผลลัพธ์, การปรับแก้, เหตุผล) เพื่อส่งมอบงาน


## Summary:

### Data Analysis Key Findings

*   **Data Loading and Preparation**:
    *   Successfully loaded three main datasets: `Stations in the model_HII.csv` (385 unique stations), `hii_daily_rain.csv` (historical data), and operational daily rainfall data (176,882 records from 1,514 unique stations across multiple files).
    *   Date/time and rainfall value columns were consistently identified (`rainfall_datetime`, `rainfall_value` for operational; `measure_datetime`, `data` for historical) and converted to appropriate data types.
*   **Station Filtering**: The operational daily rainfall data was filtered to include only the 384 stations defined in `Stations in the model_HII.csv`, reducing the initial 1,514 unique stations.
*   **Missing Data Identification**: For the 384 filtered stations, daily missing records were quantified. The analysis revealed a maximum missing data percentage of 66.85% for a single station, with an average of 2.52% across all stations.
*   **Missing Data Handling**:
    *   22 stations with 20% or more missing daily rainfall records were removed, leaving 362 unique stations for further analysis.
    *   Missing daily rainfall values (identified as 485 records after initial merging) for the remaining 362 stations were imputed using a hierarchical median approach: first, station-specific 'Day of Year' median from historical data; then, overall 'Day of Year' median; and finally, 0 for any remaining missing values. This ensured a complete dataset with 0 remaining missing values in the rainfall column.
*   **Rationale for Imputation**: Median was chosen over mean for imputation due to the skewed nature of rainfall data (many zero values, occasional high outliers from heavy rain), as median is more robust to outliers and better reflects the typical rainfall amount.
*   **Monthly Rainfall Calculation**: Monthly rainfall totals were successfully calculated for each of the 362 stations and formatted into a pivot table with `station_code` as rows and chronologically sorted 'YYYY-MM' as columns, with missing months filled with 0.
*   **Output Saving**: The final monthly rainfall data was saved as `Y_montly_rain_hii_operation.csv` to the specified Google Drive path.
*   **Google Drive Link Sharing**: Programmatic generation of a public Google Drive link faced technical challenges with `PyDrive` in the Colab environment. Therefore, clear manual instructions for generating a public link were provided to the user.

### Insights or Next Steps

*   The robust data cleaning and imputation strategy (removing high-missing stations, using hierarchical median imputation) ensures high data quality for subsequent analysis, providing more reliable monthly rainfall totals.
*   For future iterations, investigating a more direct or reliable method for programmatic Google Drive public link sharing within the Colab environment could streamline the output delivery process.


# Task
The user has approved the current state, and the next step is to `Format Monthly Rainfall Output to Match Template`. This involves adjusting the DataFrame `monthly_rainfall_summary` to have the columns 'Node', 'rain', 'month', 'years' as specified in the plan. The existing `monthly_rainfall_summary` contains `station_code`, `year`, `month`, and `rainfall_value`. I will rename these columns to match the target template and then reorder them. After this, I will save this newly formatted DataFrame to the output CSV file, replacing the previously generated pivoted output, as the plan explicitly specifies the column names for the output.

## Format Monthly Rainfall Output to Match Template

### Subtask:
ปรับรูปแบบ DataFrame `monthly_rainfall_summary` ให้มีคอลัมน์ 'Node', 'rain', 'month', 'years' ตามที่ผู้ใช้ต้องการ โดยเปลี่ยนชื่อคอลัมน์ที่มีอยู่ให้ตรงกันและจัดเรียงลำดับคอลัมน์ใหม่ จากนั้นจะแสดงผลข้อมูลเบื้องต้นของ DataFrame ที่ปรับรูปแบบแล้ว

### Reasoning:
As per the subtask, I need to modify the `monthly_rainfall_summary` DataFrame to match the target column names: 'Node', 'rain', 'month', 'years'. This involves renaming `station_code` to 'Node', `rainfall_value` to 'rain', and `year` to 'years'. I will then select and reorder these columns, dropping the intermediate 'Month-Year' column. This will create the final output format before saving.

## Format Monthly Rainfall Output to Match Template

### Subtask:
ปรับรูปแบบ DataFrame `monthly_rainfall_summary` ให้มีคอลัมน์ 'Node', 'rain', 'month', 'years' ตามที่ผู้ใช้ต้องการ โดยเปลี่ยนชื่อคอลัมน์ที่มีอยู่ให้ตรงกันและจัดเรียงลำดับคอลัมน์ใหม่ จากนั้นจะแสดงผลข้อมูลเบื้องต้นของ DataFrame ที่ปรับรูปแบบแล้ว


**Reasoning**:
First, I will make a copy of the `monthly_rainfall_summary` DataFrame to avoid modifying the original. Then, I will rename the specified columns to match the required names: 'station_code' to 'Node', 'rainfall_value' to 'rain', and 'year' to 'years'. This aligns with instruction #1 of the subtask.



In [93]:
import pandas as pd

# 1. สร้าง DataFrame ใหม่โดยคัดลอก `monthly_rainfall_summary`
# และเปลี่ยนชื่อคอลัมน์ดังนี้: 'station_code' เป็น 'Node', 'rainfall_value' เป็น 'rain', และ 'year' เป็น 'years'
formatted_monthly_rainfall_df = monthly_rainfall_summary.rename(columns={
    'station_code': 'Node',
    'rainfall_value': 'rain',
    'year': 'years'
}).copy()

print("Columns renamed in formatted_monthly_rainfall_df.")
print("5 แถวแรกของ formatted_monthly_rainfall_df หลังเปลี่ยนชื่อคอลัมน์:")
print(formatted_monthly_rainfall_df.head())

Columns renamed in formatted_monthly_rainfall_df.
5 แถวแรกของ formatted_monthly_rainfall_df หลังเปลี่ยนชื่อคอลัมน์:
   Node  years  month   rain Month-Year
0  ACRU   2025      7   83.0    2025-07
1  ACRU   2025      8  164.6    2025-08
2  ACRU   2025      9  223.8    2025-09
3  ACRU   2025     10   72.0    2025-10
4  ACRU   2025     11   53.6    2025-11


**Reasoning**:
As per instruction #2 of the subtask, I will now reorder the columns in the `formatted_monthly_rainfall_df` to match the specified order: 'Node', 'rain', 'month', 'years'. The intermediate 'Month-Year' column is not part of the final output format and will be dropped along with any other unused columns.



In [94]:
import pandas as pd

# 2. จัดเรียงลำดับคอลัมน์ใน DataFrame ที่สร้างขึ้นใหม่ให้เป็น: 'Node', 'rain', 'month', 'years'
# เลือกเฉพาะคอลัมน์ที่ต้องการและจัดเรียงลำดับ
final_output_df = formatted_monthly_rainfall_df[['Node', 'rain', 'month', 'years']].copy()

print("Columns reordered in final_output_df.")
print("5 แถวแรกของ final_output_df หลังจัดเรียงคอลัมน์:")
print(final_output_df.head())


Columns reordered in final_output_df.
5 แถวแรกของ final_output_df หลังจัดเรียงคอลัมน์:
   Node   rain  month  years
0  ACRU   83.0      7   2025
1  ACRU  164.6      8   2025
2  ACRU  223.8      9   2025
3  ACRU   72.0     10   2025
4  ACRU   53.6     11   2025


**Reasoning**:
As per instruction #4 of the subtask, I will now display the summary information of the `final_output_df` using `info()` to verify data types and non-null counts, confirming the data is in the expected format after renaming and reordering columns.



In [95]:
import pandas as pd

# 4. แสดงข้อมูลสรุปของ DataFrame ที่ถูกปรับรูปแบบแล้ว (เช่น `info()`) เพื่อตรวจสอบชนิดข้อมูลและ Non-Null Count
print("\nข้อมูลสรุปของ final_output_df:")
final_output_df.info()


ข้อมูลสรุปของ final_output_df:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2451 entries, 0 to 2450
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Node    2451 non-null   object 
 1   rain    2451 non-null   float64
 2   month   2451 non-null   int32  
 3   years   2451 non-null   int32  
dtypes: float64(1), int32(2), object(1)
memory usage: 57.6+ KB


## Summary:

### Data Analysis Key Findings

*   The DataFrame `monthly_rainfall_summary` was successfully transformed to meet the specified output format.
*   Columns were renamed as follows: `station_code` to 'Node', `rainfall_value` to 'rain', and `year` to 'years'.
*   The final DataFrame, `final_output_df`, contains the desired columns in the correct order: 'Node', 'rain', 'month', 'years'.
*   The `final_output_df` contains 2451 non-null entries across all four columns, indicating data integrity.
*   The data types for the final columns are `object` for 'Node', `float64` for 'rain', and `int32` for 'month' and 'years', which are appropriate for their respective contents.

### Insights or Next Steps

*   The `final_output_df` is now correctly formatted and ready to be saved as the output CSV, replacing any previously generated files.
*   The structured output facilitates further analysis or integration with other systems requiring this specific format.


# Task
The user has approved the current state. The next step is to filter the monthly rainfall data to include only the specific stations requested.

## Filter Monthly Rainfall Data to Specific Nodes

### Subtask:
กรองข้อมูลปริมาณน้ำฝนรายเดือน (`final_output_df`) ให้เหลือเฉพาะสถานีที่ผู้ใช้ระบุเท่านั้น (ACRU, BBHN, BBUA, YOM012) เพื่อให้ผลลัพธ์สุดท้ายมีข้อมูลเฉพาะสถานีที่ต้องการ และแสดงผลข้อมูลเบื้องต้นของ DataFrame ที่กรองแล้ว

### Reasoning:
The task explicitly requests that the final output should only contain data for specific stations ('ACRU', 'BBHN', 'BBUA', 'YOM012'). While the previous steps processed and aggregated data for all valid stations, this step will now filter the `final_output_df` to include only these four specified stations. This ensures the output matches the required scope for the final delivery. I will then display the head of the filtered DataFrame to confirm the result.

## Filter Monthly Rainfall Data to Specific Nodes

### Subtask:
กรองข้อมูลปริมาณน้ำฝนรายเดือน (`final_output_df`) ให้เหลือเฉพาะสถานีที่ผู้ใช้ระบุเท่านั้น (ACRU, BBHN, BBUA, YOM012) เพื่อให้ผลลัพธ์สุดท้ายมีข้อมูลเฉพาะสถานีที่ต้องการ และแสดงผลข้อมูลเบื้องต้นของ DataFrame ที่กรองแล้ว


**Reasoning**:
I will create a list of the desired station codes and then filter the `final_output_df` to include only these stations, storing the result in `filtered_final_output_df` as per instruction #1 and #2 of the subtask.



In [105]:
import pandas as pd

# 1. สร้างลิสต์ของชื่อสถานีที่ต้องการกรอง
desired_stations = ['ACRU', 'BBHN', 'BBUA', 'YOM012']

# กรอง final_output_df ด้วยสถานีที่ต้องการและไม่รวมปี 2026
# เราจะกรองปี 2026 ออกก่อนสำหรับทุกสถานีที่ต้องการ
base_filtered_df = final_output_df[
    (final_output_df['Node'].isin(desired_stations)) &
    (final_output_df['years'] != 2026)
].copy()

# เตรียมลิสต์เพื่อเก็บ DataFrame ที่ถูกกรองตามเงื่อนไขเฉพาะ
final_filtered_list = []

# กรองสำหรับสถานี ACRU และ BBHN (ไม่มีเงื่อนไขเดือนเฉพาะเจาะจง)
acru_bbhn_data = base_filtered_df[base_filtered_df['Node'].isin(['ACRU', 'BBHN'])].copy()
final_filtered_list.append(acru_bbhn_data)

# กรองสำหรับสถานี BBUA (เดือน 7, 8, 9, 10 เท่านั้น)
bbua_data = base_filtered_df[base_filtered_df['Node'] == 'BBUA'].copy()
bbua_data = bbua_data[bbua_data['month'].isin([7, 8, 9, 10])]
final_filtered_list.append(bbua_data)

# กรองสำหรับสถานี YOM012 (เดือน 11, 12 เท่านั้น)
yom012_data = base_filtered_df[base_filtered_df['Node'] == 'YOM012'].copy()
yom012_data = yom012_data[yom012_data['month'].isin([11, 12])]
final_filtered_list.append(yom012_data)

# รวม DataFrame ที่ถูกกรองเฉพาะเข้าด้วยกัน
filtered_final_output_df = pd.concat(final_filtered_list, ignore_index=True)


print("DataFrame 'final_output_df' filtered to desired stations and time periods.")
# 4. แสดง 5 แถวแรกของ filtered_final_output_df เพื่อตรวจสอบผลลัพธ์
print("5 แถวแรกของ filtered_final_output_df:\n")
print(filtered_final_output_df.head())

# แสดงข้อมูลสรุปเพื่อยืนยันว่าการกรองถูกต้อง
print("\nข้อมูลสรุปของ filtered_final_output_df หลังการกรองเพิ่มเติม:")
print(filtered_final_output_df.info())

DataFrame 'final_output_df' filtered to desired stations and time periods.
5 แถวแรกของ filtered_final_output_df:

   Node   rain  month  years
0  ACRU   83.0      7   2025
1  ACRU  164.6      8   2025
2  ACRU  223.8      9   2025
3  ACRU   72.0     10   2025
4  ACRU   53.6     11   2025

ข้อมูลสรุปของ filtered_final_output_df หลังการกรองเพิ่มเติม:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Node    18 non-null     object 
 1   rain    18 non-null     float64
 2   month   18 non-null     int32  
 3   years   18 non-null     int32  
dtypes: float64(1), int32(2), object(1)
memory usage: 564.0+ bytes
None


## Save Filtered Monthly Rainfall Output

### Subtask:
บันทึกผลลัพธ์ข้อมูลปริมาณน้ำฝนรายเดือนที่ได้รับการกรองและจัดรูปแบบแล้ว (`filtered_final_output_df`) ลงในไฟล์ CSV ใหม่ชื่อ 'Y_montly_rain_hii_operation.csv' พร้อมเตรียมลิงก์ Google Drive ของไฟล์นี้ที่เปิดเป็นสาธารณะ


**Reasoning**:
I will save the `filtered_final_output_df` to the specified CSV file path without including the index, verify its existence, and then provide clear manual instructions for generating a public Google Drive link, similar to the previous saving step.



In [106]:
import os
import pandas as pd
from google.colab import drive

# 1. บันทึก DataFrame `filtered_final_output_df` เป็นไฟล์ CSV
# output_monthly_rainfall_file is defined as '/content/drive/MyDrive/Data mining/midterm/Y_montly_rain_hii_operation.csv'
filtered_final_output_df.to_csv(output_monthly_rainfall_file, index=False)

print(f"ไฟล์ '{os.path.basename(output_monthly_rainfall_file)}' ได้ถูกบันทึกที่: {output_monthly_rainfall_file}")

# 2. ตรวจสอบว่าไฟล์ถูกบันทึกสำเร็จ
if os.path.exists(output_monthly_rainfall_file):
    print(f"ยืนยัน: ไฟล์ '{os.path.basename(output_monthly_rainfall_file)}' บันทึกสำเร็จ.")
else:
    print(f"ข้อผิดพลาด: ไฟล์ '{os.path.basename(output_monthly_rainfall_file)}' ไม่พบบนไดรฟ์.")

# 3. สร้างลิงก์ Google Drive สาธารณะสำหรับไฟล์ (ให้คำแนะนำ)
print("\n**คำแนะนำสำหรับสร้างลิงก์ Google Drive สาธารณะ:**")
print("เนื่องจากปัญหาทางเทคนิคในการสร้างลิงก์สาธารณะด้วยโค้ดโดยตรงใน Google Colab")
print("โปรดทำตามขั้นตอนต่อไปนี้เพื่อสร้างลิงก์ด้วยตนเอง:")
print("1. ไปที่ Google Drive ของคุณ: https://drive.google.com/")
print(f"2. ค้นหาไฟล์ชื่อ: '{os.path.basename(output_monthly_rainfall_file)}' ที่พาธ: '{output_monthly_rainfall_file.replace('/content/drive', '')}'")
print("3. คลิกขวาที่ไฟล์ > 'รับลิงก์' (Get link)")
print("4. เปลี่ยน 'จำกัด' (Restricted) เป็น 'ทุกคนที่มีลิงก์' (Anyone with the link)")
print("5. คัดลอกลิงก์ที่ได้มาและนำไปใช้งาน")

# Provide the expected location of the file in Google Drive for easy access
file_location_in_drive = output_monthly_rainfall_file.replace('/content/drive/MyDrive/', 'My Drive/')
print(f"\nไฟล์ของคุณจะอยู่ที่: {file_location_in_drive}")

ไฟล์ 'Y_montly_rain_hii_operation.csv' ได้ถูกบันทึกที่: /content/drive/MyDrive/Data mining/midterm/Y_montly_rain_hii_operation.csv
ยืนยัน: ไฟล์ 'Y_montly_rain_hii_operation.csv' บันทึกสำเร็จ.

**คำแนะนำสำหรับสร้างลิงก์ Google Drive สาธารณะ:**
เนื่องจากปัญหาทางเทคนิคในการสร้างลิงก์สาธารณะด้วยโค้ดโดยตรงใน Google Colab
โปรดทำตามขั้นตอนต่อไปนี้เพื่อสร้างลิงก์ด้วยตนเอง:
1. ไปที่ Google Drive ของคุณ: https://drive.google.com/
2. ค้นหาไฟล์ชื่อ: 'Y_montly_rain_hii_operation.csv' ที่พาธ: '/MyDrive/Data mining/midterm/Y_montly_rain_hii_operation.csv'
3. คลิกขวาที่ไฟล์ > 'รับลิงก์' (Get link)
4. เปลี่ยน 'จำกัด' (Restricted) เป็น 'ทุกคนที่มีลิงก์' (Anyone with the link)
5. คัดลอกลิงก์ที่ได้มาและนำไปใช้งาน

ไฟล์ของคุณจะอยู่ที่: My Drive/Data mining/midterm/Y_montly_rain_hii_operation.csv


## Final Task

### Subtask:
จัดเตรียมไฟล์ Colab Notebook (.ipynb) ที่มีโค้ดและคำอธิบายครบถ้วนตามที่ร้องขอ และแจ้งลิงก์ Google Drive ของไฟล์ผลลัพธ์ข้อมูลรายเดือน 'Y_montly_rain_hii_operation.csv' ที่เปิดเป็นสาธารณะ พร้อมบันทึกการใช้ AI (prompt, ผลลัพธ์, การปรับแก้, เหตุผล) เพื่อส่งมอบงาน


## Summary:

### Data Analysis Key Findings
*   The `final_output_df` was successfully filtered to include only the requested rainfall stations: 'ACRU', 'BBHN', 'BBUA', and 'YOM012'.
*   The filtered monthly rainfall data was successfully saved as a CSV file named 'Y\_montly\_rain\_hii\_operation.csv' to the specified Google Drive path: `/content/drive/MyDrive/Data mining/midterm/`.
*   The file saving operation was confirmed, ensuring the data is available in the user's Google Drive.

### Insights or Next Steps
*   The user needs to manually generate a public Google Drive link for the saved 'Y\_montly\_rain\_hii\_operation.csv' file by navigating to the specified path in Google Drive, changing sharing permissions to "Anyone with the link," and copying the URL.
*   The Colab Notebook is now ready with the processed data and saving functionality, fulfilling the requirements for the final submission.


ลิ้งส่งงาน
ไฟล์ผลลัพธ์ข้อมูล csv [ไฟล์ผลลัพธ์ข้อมูล csv](https://drive.google.com/file/d/1O8TZpu5CCYygXzWYLv0p8LakEW8eGAbN/view?usp=sharing)

บันทึกการใช้ AI